<!DOCTYpE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Kafillik shartnomasi</title>
    <style type="text/css">
        html {
            line-height: 1.15;
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%
        }

        article,
        aside,
        footer,
        header,
        nav,
        section {
            display: block
        }

        h1 {
            font-size: 24px
        }

        h2 {
            font-size: 20px
        }

        .m-5 {
            margin-top: 5px;
        }

        @page {
            margin: 0
        }

        body {
            margin: 0
        }

        .sheet {
            margin: 0;
            overflow: hidden;
            position: relative;
            box-sizing: border-box;
            page-break-after: always
        }

        .landscape-page {
            overflow: hidden;
            position: relative;
            box-sizing: border-box;
            page-break-after: always;
            width: 296mm;
            height: 210mm;
            margin: 0 auto;
        }

        body.A3 .sheet {
            width: 297mm;
            height: 419mm;
            margin-left: auto;
            margin-right: auto
        }

        body.A3 .landscape.sheet {
            width: 420mm;
            height: 296mm;
            margin-left: auto;
            margin-right: auto
        }

        body.A4 .sheet,
        body.A4 .landscape.sheet {
            width: 210mm;
            height: 296mm;
            margin-left: auto;
            margin-right: auto
        }

        body.A4 .landscape.sheet {
            margin-top: -160px;
            margin-bottom: -160px;
            -webkit-transform: rotate(90deg);
            -moz-transform: rotate(90deg);
            -o-transform: rotate(90deg);
            -ms-transform: rotate(90deg);
            transform: rotate(90deg)
        }

        body.A4 .landscape.sheet .content {
            width: 278mm;
            height: 209mm;
            margin: 105px 0 0 -100px;
            -webkit-transform: rotate(-90deg);
            -moz-transform: rotate(-90deg);
            -o-transform: rotate(-90deg);
            -ms-transform: rotate(-90deg);
            transform: rotate(-90deg)
        }

        body.A5 .sheet {
            width: 148mm;
            height: 209mm;
            margin-left: auto;
            margin-right: auto
        }

        body.A5 .landscape.sheet {
            width: 210mm;
            height: 147mm;
            margin-left: auto;
            margin-right: auto
        }

        .landscape.sheet.padding-standart {
            padding: 15mm 10mm 10mm 10mm;
        }

        .sheet.padding-standart {
            padding: 15mm 15mm 20mm 30mm;
        }

        .sheet.padding-10mm {
            padding: 10mm
        }

        .sheet.padding-15mm {
            padding: 15mm
        }

        .sheet.padding-20mm {
            padding: 20mm
        }

        .sheet.padding-25mm {
            padding: 25mm
        }

        .sheet.continuous {
            margin: 0
        }

        @media screen {
            body {
                background: #e0e0e0
            }

            .sheet {
                background: white;
                box-shadow: 0 .5mm 2mm rgba(0, 0, 0, .3);
                margin: 5mm
            }

            .landscape-page {
                background: white;
                box-shadow: 0 .5mm 2mm rgba(0, 0, 0, .3);
                /*margin:5mm*/
            }
        }

        @media print {
            body.A3 .landscape {
                width: 420mm;
            }

            body.A3 {
                width: 297mm;
            }

            body.A4 .landscape.sheet {
                margin-top: auto;
                margin-bottom: auto;
                -webkit-transform: rotate(0deg);
                -moz-transform: rotate(0deg);
                -o-transform: rotate(0deg);
                -ms-transform: rotate(0deg);
                transform: rotate(0deg)
            }

            body.A4,
            body.A5 .landscape {
                width: 210mm
            }

            body.A5 {
                width: 148mm
            }

            .landscape-page {
                width: 296mm;
            }

        }

        @media print {

            body,
            page {
                margin: 0;
                box-shadow: 0 0 0 rgba(0, 0, 0, 0);
            }

            @page {
                size: A4;
                margin: 0;
            }
        }

        * {
            margin: 0;
            padding: 0;
            font-size: 14px;
            line-height: 18px
        }

        body {
            background: rgb(204, 204, 204);
        }

        page {
            background: white;
            display: block;
            margin: 0.5cm;
            box-shadow: 0 0 0.5cm rgba(0, 0, 0, 0.5);
        }

        page[size="A4"] {
            width: 21cm;
            height: 29.7cm;
        }

        table {
            border-collapse: collapse;
            border: 0px solid #000;
            margin: 4px 0 0 0;
            width: 100%;
            line-height: 1.15
        }

        .landscape.sheet table th {
            padding: 0px;
            font-size: 12px
        }

        .landscape.sheet table td {
            padding: 1px 5px;
            font-size: 12px;
            text-indent: 0px
        }

        .sheet table th {
            padding: 4px 2px;
            font-size: 14px
        }

        .sheet table td {
            padding: 2px 2px 2px 2px;
            font-size: 14px;
            text-indent: 0px
        }

        table.clean th {
            padding: 2px 6px;
            font-size: 12px;
            text-indent: 0px;
            font-weight: normal
        }

        .page_number {
            position: absolute;
            margin-left: auto;
            margin-right: auto;
            left: 0;
            right: 0;
            text-align: center;
            bottom: 15px;
            font-family: Calibri;
            font-size: 12pt
        }

        p {
            text-indent: 40px;
            margin: 0;
            text-align: justify;
            font-size: 14px;
        }

        .noTextIndent {
            text-indent: 0px;
        }

        thead tr th,
        tbody tr th,
        tbody tr td {
            text-align: center;
        }

        .part11t {
            border: 1px solid black;
        }

        br {
            line-height: 1em;
        }

        .h4,
        .h5,
        .h6,
        h4,
        h5,
        h6 {
            margin-top: 10px !important;
            margin-bottom: 10px !important;
            font-size: 16px !important
        }

        table tr {
            border: 1px solid black;
        }

        table td {
            padding: 2px;
            font-size: 19px;
            text-indent: 0px;
            text-align: start;
            border: 1px solid black;
            font-weight: normal;
        }

        .readonly-color td {
            font-size: 20px !important;
            padding: 5px !important;
        }
        .bold_color{
            font-weight: bold;
        }
    </style>
</head>

<body class="A4">
    <section class="sheet padding-standart">
        <div>
            <div style="display:flex;justify-content: end;align-items: end; flex-direction: column;">
                <p style="text-align:center;">
                    «ТАСДИҚЛАЙМАН»
                </p>
                <br>
                <br>
                <p style="text-align:center;">
                    ${model.client_name}
                </p>
                <br>
                <br>
                <p style="text-align:center;">
                    ${model.client_info}
                </p>
                <br>
                <br>
              <#assign sumColumn = (model.cal_reserve[model.cal_reserve?size-1].list[0]*model.other_costs.materialStorage+model.cost_productions[1].sum_value*model.other_costs.materialWarehouse)/360>
                <p style="text-align:center;">
                    ${model.created_at}, ${sumColumn}
                </p>
            </div>
            <div
                style="display:flex;justify-content: center;align-items: center;flex-direction: column;position: absolute;top: 50%;width: 100%;left: 0;">
                <p style="font-weight: bold;font-size: 24px;width: 90%;text-align: center;"> ${model.purpose} </p>
                <br>
                <br>
                <br>
                <p style="font-weight: bold;font-size: 32px;"> Б И З Н Е С - Р Е Ж А </p>
            </div>
            <div
                style="display:flex;justify-content: center;align-items: center;flex-direction: column;position:absolute;bottom: 60px;width: 100%;right: 1px;">
                <p style="font-weight: bold;"> ${model.region_info} </p>
            </div>
        </div>
    </section>
    <section class="sheet padding-standart">
        <table>
            <thead>
                <tr>
                    <th colspan="2" style="font-weight: bold; font-size: 24px;">
                        ТАШАББУСКОР ҚЎЙИДАГИЛАРНИ ТАҚДИМОТ ҚИЛАДИ
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr class="readonly-color rows-table">
                    <td style="font-weight: bold;">1.</td>
                    <td style="text-align: start; font-weight: bold;">Лойиҳа ташаббускори номи</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>2.</td>
                    <td>Қайси мулкчилик шаклида фаолият кўрсатмоқда</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>3.</td>
                    <td>Қачон ташкил этилган</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>4.</td>
                    <td>Йўлга қўйган бизнес лойиҳаси</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>5.</td>
                    <td>Яратилган иш ўрни</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>6.</td>
                    <td>Режалаштирган лойиҳаси</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td></td>
                    <td>Кредитни қайси мақсадга ва қанча миқдорда олмоқчи (лойиҳа қийматининг кўпи билан 70 фоизгача)
                    </td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td></td>
                    <td>Лойиҳада ўз маблағи билан иштироки (лойиҳа қийматининг камида 30 фоизи бўлиши, шундан қанча
                        қисми пул маблағи билан, хом-ашё билан, ускуналар билан ёки бино-иншоот билан иштирокини маълум
                        қилади)</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>7.</td>
                    <td>Яратиладиган иш ўрни</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>8.</td>
                    <td>Қарорда белгиланган жисмоний шахслардан бири бўлмҳсангиз, тадбиркорлик фаолиятингизни
                        бошлашингиз учун қайси мулкчилик шаклдаги тадбиркорлик субъекти сифатида рўйхатдан ўтмоқчисиз
                        (ЯТТ, ОК, ХК, МЧЖ, НТТ ....)</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>9.</td>
                    <td>Бир бирлик маҳсулот учун хом-ашё ҳаражати таркиби, тайёр маҳсулот номи, уни сотиш қиймати</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>10.</td>
                    <td>Тайёр маҳсулотларни сотиш бўйича бозор таҳлили</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td></td>
                    <td>..........</td>
                </tr>
                <tr class="readonly-color rows-table">
                    <td>11.</td>
                    <td>Даромади қанча, кредит фоизи ва асосий қарз жами қанча қайтаради ва соф фойда қанча олади</td>
                </tr>
            </tbody>
        </table>
    </section>


    <section class="sheet padding-standart" style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="4" style="font-weight: bold; font-size: 24px;">
                                Банк кредити
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="">
                            <td style="font-weight: normal" colspan="1">ЛОЙИҲА НОМИ</td>
                            <td colspan="3" style="font-weight: bold"> ${model.purpose} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: bold" colspan="2">ЛОЙИҲА БЎЙИЧА МАЪЛУМОТ</td>
                            <td style="font-weight: bold" colspan="2"> ЛОЙИҲА ТАШАББУСКОРИ </td>
                        </tr>
                        <tr class="">
                            <td colspan="1" style="font-weight: normal">Ишлаб чиқариладиган маҳсулот</td>
                            <td style="font-weight: bold" colspan="1"> ${model.purpose} </td>
                            <td style="font-weight: normal"> Номи </td>
                            <td style="font-weight: bold"> ${model.client_name} </td>
                        </tr>
                        <tr class="">
                            <td colspan="1" style="font-weight: normal">Ишлаб чиқариш қуввати</td>
                            <td colspan="1"> </td>
                            <td style="font-weight: normal"> Манзили </td>
                            <td style="font-weight: normal"> ${model.address} </td>
                        </tr>
                        <tr class="">
                            <td colspan="1" style="font-weight: normal">ЛОЙИҲАНИНГ УМУМИЙ ҚИЙМАТИ (минг сўм)</td>
                            <td colspan="1" style="font-weight: normal"> ${model.credit_sum + model.own_sum} </td>
                            <td style="font-weight: normal"> Рахбарияти </td>
                            <td style="font-weight: normal"> ${model.director_name!"-"} </td>
                        </tr>
                        <tr class="">
                            <td colspan="1" style="font-weight: normal">Ўз улуши </td>
                            <td colspan="1" style="font-weight: normal"> ${model.own_sum} </td>
                            <td style="font-weight: normal"> Банк реквизитлари </td>
                            <td style="font-weight: normal"> ${model.mfo} </td>
                        </tr>
                        <tr class="">
                            <td colspan="1" style="font-weight: normal">Банк кредити</td>
                            <td colspan="1" style="font-weight: normal"> ${model.credit_sum} </td>
                            <td style="font-weight: normal"> Телефон </td>
                            <td style="font-weight: normal"> ${model.client_phone_number} </td>
                        </tr>
                    </tbody>
                </table>
                <br>
                <table style="width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="5" style="font-weight: bold; font-size: 24px;">
                                Лойиҳа умумий қиймати
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="">
                            <td style="font-weight: bold" colspan="1">Курсаткичлар</td>
                            <td colspan="1" style="font-weight: normal"> Уз улуши </td>
                            <td style="font-weight: normal"> Банк кредити </td>
                            <td style="font-weight: bold"> Жами </td>
                            <td style="font-weight: bold"> Таркиби (%) </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: normal" colspan="1">Асосий воситалар ва ускуналар</td>
                            <td colspan="1" style="font-weight: normal"> ${model.own_technique_sum} </td>
                            <td style="font-weight: normal"> ${model.credit_technique_sum} </td>
                            <td style="font-weight: normal"> ${model.own_technique_sum + model.credit_technique_sum}
                            </td>
                            <td style="font-weight: normal"> ${(model.own_technique_sum +
                                model.credit_technique_sum)*100/(model.own_financial_sum + model.own_material_sum +
                                model.own_technique_sum + model.credit_sum*0.01 + model.credit_sum)} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: normal" colspan="1">Айланма маблағлар</td>
                            <td colspan="1" style="font-weight: normal"> ${model.own_material_sum} </td>
                            <td style="font-weight: normal"> ${model.credit_material_sum} </td>
                            <td style="font-weight: normal"> ${model.credit_material_sum + model.own_material_sum} </td>
                            <td style="font-weight: normal"> ${(model.credit_material_sum +
                                model.own_material_sum)*100/(model.own_financial_sum + model.own_material_sum +
                                model.own_technique_sum + model.credit_sum*0.01 + model.credit_sum)} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: normal" colspan="1">Лойиҳа ташаббускорининг ўз ҳисобидан киритадиган
                                товар, пул ёки улуш миқдори</td>
                            <td colspan="1" style="font-weight: normal"> 0 </td>
                            <td style="font-weight: normal"> 0 </td>
                            <td style="font-weight: normal"> 0 </td>
                            <td style="font-weight: normal"> 0 </td>
                        </tr>
                        <tr class="">
                            <td colspan="1" style="font-weight: normal"> Лойиҳани амалга оширишдаги молиявий харажатлар
                            </td>
                            <td colspan="1" style="font-weight: normal"> ${model.own_financial_sum} </td>
                            <td style="font-weight: normal"> ${model.financial_sum} </td>
                            <td style="font-weight: normal"> ${model.own_financial_sum+ model.financial_sum} </td>
                            <td style="font-weight: normal"> ${(model.own_financial_sum+
                                model.financial_sum)*100/(model.own_financial_sum + model.own_material_sum +
                                model.own_technique_sum + model.credit_sum*0.01 + model.credit_sum)} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: normal" colspan="1"> Жами Ўзгармас активлар </td>
                            <td style="font-weight: normal" colspan="1"> ${model.own_financial_sum +
                                model.own_material_sum + model.own_technique_sum} </td>
                            <td style="font-weight: normal"> ${model.credit_sum} </td>
                            <td style="font-weight: normal"> ${model.own_financial_sum + model.own_material_sum +
                                model.own_technique_sum + model.credit_sum} </td>
                            <td style="font-weight: normal">
                                ${ (model.own_financial_sum + model.own_material_sum + model.own_technique_sum +
                                model.credit_sum)*100/(model.own_financial_sum + model.own_material_sum +
                                model.own_technique_sum + model.credit_sum*0.01 + model.credit_sum)}
                            </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: normal" colspan="1"> Молиявий харажатлар </td>
                            <td colspan="1" style="font-weight: normal"> ${model.credit_sum*0.01} </td>
                            <td style="font-weight: normal"> 0 </td>
                            <td style="font-weight: normal"> ${model.credit_sum*0.01} </td>
                            <td style="font-weight: normal">
                                ${model.credit_sum*0.01*100/(model.own_financial_sum + model.own_material_sum +
                                model.own_technique_sum + model.credit_sum*0.01 + model.credit_sum)}
                            </td>
                        </tr>
                        <tr class="">
                            <td colspan="1"> ЛОЙИҲА УМУМИЙ ҚИЙМАТИ </td>
                            <td colspan="1"> ${model.own_financial_sum + model.own_material_sum +
                                model.own_technique_sum + model.credit_sum*0.01} </td>
                            <td> ${model.credit_sum} </td>
                            <td> ${model.own_financial_sum + model.own_material_sum + model.own_technique_sum +
                                model.credit_sum*0.01 + model.credit_sum} </td>
                            <td> 100 </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="sheet padding-standart" style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="7" style="font-weight: bold; font-size: 24px;">
                                МОЛИЯВИЙ РЕЖА (сумда)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="">
                            <td style="font-weight: bold" colspan="1">Курсаткичлар</td>
                            <td colspan="1" style="font-weight: normal"> Уз улуши </td>
                            <td style="font-weight: normal"> Банк кредити </td>
                            <td style="font-weight: bold"> Жами </td>
                            <td style="font-weight: bold" colspan="2"> СТРУКТУРА (%) </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: bold" colspan="1">ЎЗ УЛУШИ (сўм)</td>
                            <td colspan="1" style="font-weight: normal"> </td>
                            <td style="font-weight: normal"> </td>
                            <td style="font-weight: bold"> </td>
                            <td style="font-weight: bold"> </td>
                            <td style="font-weight: bold"> </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: normal" colspan="1"> Молиявий харажатлар </td>
                            <td colspan="1" style="font-weight: normal; text-align: center"> ${model.credit_sum*0.01}
                            </td>
                            <td style="font-weight: normal; text-align: center"> 0 </td>
                            <td style="font-weight: normal; text-align: center"> ${model.credit_sum*0.01} </td>
                            <td style="font-weight: normal ; text-align: center"> ${(model.credit_sum)/(model.credit_sum
                                + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum +
                                model.own_financial_sum)} </td>
                            <td style="font-weight: bold ; text-align: center" rowspan="5">
                                ${((model.credit_sum*0.01 + model.own_technique_sum + model.own_sum +
                                model.own_financial_sum) * 100)/(model.credit_sum + model.credit_sum*0.01 +
                                model.own_technique_sum + model.own_sum + model.own_financial_sum)}
                            </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: normal" colspan="1">Асосий воситалар ва ускуналар</td>
                            <td colspan="1" style="font-weight: normal; text-align: center"> ${model.own_technique_sum}
                            </td>
                            <td style="font-weight: normal; text-align: center"> 0 </td>
                            <td style="font-weight: normal; text-align: center"> ${model.own_technique_sum} </td>
                            <td style="font-weight: normal; text-align: center"> ${(model.own_technique_sum *
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: norma; text-align: centerl" colspan="1">Айланма маблағлар</td>
                            <td colspan="1" style="font-weight: normal; text-align: center"> ${model.own_material_sum}
                            </td>
                            <td style="font-weight: normal; text-align: center"> 0 </td>
                            <td style="font-weight: normal; text-align: center"> ${model.own_material_sum} </td>
                            <td style="font-weight: normal; text-align: center"> ${(model.own_material_sum *
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: normal; text-align: center" colspan="1"> Лойиҳа ташаббускорининг ўз
                                ҳисобидан киритадиган товар, пул ёки улуш миқдори</td>
                            <td colspan="1" style="font-weight: normal"> ${model.own_sum} </td>
                            <td style="font-weight: normal; text-align: center"> 0 </td>
                            <td style="font-weight: normal; text-align: center"> ${model.own_sum} </td>
                            <td style="font-weight: normal; text-align: center"> ${(model.own_sum *
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)} </td>
                        </tr>
                        <tr class="">
                            <td colspan="1" style="font-weight: normal; text-align: center"> Лойиҳани амалга оширишдаги
                                молиявий харажатлар </td>
                            <td colspan="1" style="font-weight: normal; text-align: center"> ${model.own_financial_sum}
                            </td>
                            <td style="font-weight: normal; text-align: center"> 0 </td>
                            <td style="font-weight: normal; text-align: center"> ${model.own_financial_sum} </td>
                            <td style="font-weight: normal; text-align: center"> ${(model.own_financial_sum *
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: bold; text-align: center" colspan="1"> ЖАМИ УЗ УЛУШИ </td>
                            <td style="font-weight: bold; text-align: center" colspan="1">
                                ${model.credit_sum*0.01 + model.own_technique_sum + model.own_sum +
                                model.own_financial_sum}
                            </td>
                            <td style="font-weight: bold ;text-align: center"> 0 </td>
                            <td style="font-weight: bold; text-align: center">
                                ${model.credit_sum*0.01 + model.own_technique_sum + model.own_sum +
                                model.own_financial_sum}
                            </td>
                            <td style="font-weight: bold ; text-align: center"> ${((model.credit_sum*0.01 +
                                model.own_technique_sum + model.own_sum + model.own_financial_sum) *
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)} </td>
                            <td style="font-weight: bold ; text-align: center"> ${((model.credit_sum*0.01 +
                                model.own_technique_sum + model.own_sum + model.own_financial_sum) *
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)}</td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: bold" colspan="1">КРЕДИТ</td>
                            <td colspan="1" style="font-weight: normal"> </td>
                            <td style="font-weight: normal"> </td>
                            <td style="font-weight: bold"> </td>
                            <td style="font-weight: bold"> </td>
                            <td style="font-weight: bold"> </td>
                        </tr>
                        <tr class="">
                            <td style="text-align: center" colspan="1"> БАНК КРЕДИТИ </td>
                            <td style="text-align: center" colspan="1"> 0 </td>
                            <td style="text-align: center"> ${model.credit_sum} </td>
                            <td style="text-align: center"> ${model.credit_sum} </td>
                            <td style="text-align: center"> ${(model.credit_sum* 100)/(model.credit_sum +
                                model.credit_sum*0.01 + model.own_technique_sum + model.own_sum +
                                model.own_financial_sum)} </td>
                            <td style="font-weight: bold; text-align:center;" rowspan="2"> ${(model.credit_sum*
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: bold; text-align: center" colspan="1"> ЖАМИ </td>
                            <td style="font-weight: bold; text-align: center" colspan="1"> 0 </td>
                            <td style="font-weight: bold; text-align: center"> ${model.credit_sum} </td>
                            <td style="font-weight: bold; text-align: center"> ${model.credit_sum} </td>
                            <td style="font-weight: bold; text-align: center"> ${(model.credit_sum*
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)} </td>
                        </tr>
                        <tr class="">
                            <td style="font-weight: bold" colspan="1"> ЖАМИ МОЛИЯЛАШТИРИШ </td>
                            <td style="font-weight: bold" colspan="1"> ${model.credit_sum*0.01 + model.own_technique_sum
                                + model.own_sum + model.own_financial_sum} </td>
                            <td style="font-weight: bold"> ${model.credit_sum} </td>
                            <td style="font-weight: bold"> ${model.credit_sum + model.credit_sum*0.01 +
                                model.own_technique_sum + model.own_sum + model.own_financial_sum} </td>
                            <td style="font-weight: bold"> ${( (model.credit_sum + model.credit_sum*0.01 +
                                model.own_technique_sum + model.own_sum + model.own_financial_sum) *
                                100)/(model.credit_sum + model.credit_sum*0.01 + model.own_technique_sum + model.own_sum
                                + model.own_financial_sum)} </td>
                            <td style="font-weight: bold" rowspan="2"> 100 </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>



    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">

        <div style="transform: rotate(-90deg);position: absolute;top: 463px;left: -439px;width: fit-content;">
            <table style="width: 1094px;">
                <tbody>
                    <tr>
                        <th colspan="15" style="font-weight: bold;font-size: 19px;">
                            АМОРТИЗАЦИЯ
                        </th>
                    </tr>

                    <#list model.amort?if_exists as amort>
                        <#assign sIndex=amort?index + 1>
                            <tr>
                                <td style="font-size: 13px; text-align: center; border:1px solid;"> ${amort.name} </td>
                                <td style="font-size: 13px; text-align: left; border:1px solid; text-indent:5px">
                                    ${amort.allSum} </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid;">
                                    ${amort.depreciation_rate} </td>

                                <#list amort.list?keys as key>
                                    <#assign lindex=key?number>
                                        <td style="font-size: 13px; text-align: center; border: 1px solid;">
                                            <#if sIndex==1> ${lindex+1} - ${model.period_type} <#else>
                                                    ${amort.list[key]} </#if>

                                        </td>
                                </#list>

                            </tr>
                    </#list>
                </tbody>
            </table>
        </div>
    </section>



    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 1094px;">

                    <tbody>
                        <tr>
                            <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"
                                colspan="6">Ишлаб чиқариш режаси</td>
                        </tr>
                        <#list model.development_plans?if_exists as dev_plan>
                            <tr>
                                <td style="font-size: 13px; text-align: center; border:1px solid;"> ${dev_plan.name}
                                </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid;"> ${dev_plan.count}
                                </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid;"> ${dev_plan.reserve}
                                </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid;"> ${dev_plan.ex} </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid;"> ${dev_plan.internal}
                                </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid;"> ${dev_plan.external}
                                </td>
                            </tr>
                        </#list>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 1094px;">
                    <tbody>
                        <#list model.development_power?if_exists as dev_pow>
                            <#assign dpindex=dev_pow?index + 1>
                                <tr>
                                    <td
                                        style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">
                                        ${dev_pow.name} </td>
                                    <#list 1..model.period as index>
                                        <td style="font-size: 13px; text-align: center; border: 1px solid;">
                                            <#if dpindex==1> ${index} - ${model.period_type} <#else>
                                                    ${dev_pow.list[index-1]} </#if>
                                        </td>
                                    </#list>
                                </tr>
                        </#list>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 1094px;">
                    <tbody>
                        <#list model.sales_volume?if_exists as sales>
                            <#assign dpindex=sales?index + 1>
                                <tr>
                                    <td
                                        style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">
                                        ${sales.name} </td>
                                    <#list 1..model.period as index>
                                        <td style="font-size: 13px; text-align: center; border: 1px solid;">
                                            <#if dpindex==1> ${index} - ${model.period_type} <#else>
                                                    ${sales.list[index-1]} </#if>
                                        </td>
                                    </#list>
                                </tr>
                        </#list>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 1094px;">
                    <tbody>
                        <#list model.reserve?if_exists as res>
                            <#assign dpindex=res?index + 1>
                                <tr>
                                    <td
                                        style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">
                                        ${res.name} </td>
                                    <#list 1..model.period as index>
                                        <td style="font-size: 13px; text-align: center; border: 1px solid;">
                                            <#if dpindex==1> ${index} - ${model.period_type} <#else>
                                                    ${res.list[index-1]} </#if>
                                        </td>
                                    </#list>
                                </tr>
                        </#list>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 1094px;">
                    <tbody>
                        <#list model.total_sales?if_exists as tots>
                            <#assign dpindex=tots?index + 1>
                                <tr>
                                    <td
                                        style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">
                                        ${tots.name} </td>
                                    <#list 1..model.period as index>
                                        <td style="font-size: 13px; text-align: center; border: 1px solid;">
                                            <#if dpindex==1> ${index} - ${model.period_type} <#else>
                                                    ${tots.list[index-1]} </#if>
                                        </td>
                                    </#list>
                                </tr>
                        </#list>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 1094px;">
                    <tbody>
                        <#list model.internal_market?if_exists as internalm>
                            <#assign dpindex=internalm?index + 1>
                                <tr>
                                    <td
                                        style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">
                                        ${internalm.name} </td>
                                    <#list 1..model.period as index>
                                        <td style="font-size: 13px; text-align: center; border: 1px solid;">
                                            <#if dpindex==1> ${index} - ${model.period_type} <#else>
                                                    ${internalm.list[index-1]} </#if>
                                        </td>
                                    </#list>
                                </tr>
                        </#list>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <table style="width: 1094px;">
                    <tbody>
                        <#list model.external_market?if_exists as externalm>
                            <#assign dpindex=externalm?index + 1>
                                <tr>
                                    <td
                                        style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">
                                        ${externalm.name} </td>
                                    <#list 1..model.period as index>
                                        <td style="font-size: 13px; text-align: center; border: 1px solid;">
                                            <#if dpindex==1> ${index} - ${model.period_type} <#else>
                                                    ${externalm.list[index-1]} </#if>
                                        </td>
                                    </#list>
                                </tr>
                        </#list>
                    </tbody>
                </table>
            </div>
        </div>
    </section>


<section class="sheet padding-standart landscape" style="position: relative;display: flex;justify-content: flex-start;">
    <div style="display: flex; justify-content: center;">
        <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
          <h3 style="font-size: 15px; text-align: center; border:1px solid; font-weight: bold ; text-align: center;"> СОТИШ РЕЖАСИ </h3>
            <table style="width: 1094px;">
                <#list model.all_result?if_exists as row>
                    <#assign sIndex = row?index + 1>
                    <tr>
                      <#if row.key?exists && row.key == 1>
                        <#if (sIndex != 1)>
                        </tr>
                          <tr>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;" colspan="32323">  </td>
                          </tr>
                          </#if>
                                 <#assign numberOfColumns = model.period-1>
                                  <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;" >${row.name}</td>
                                 <#list 0..numberOfColumns as i>
                                   <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">${i + 1} - ${model.period_type}</td>
                                 </#list>
                                <#else>
                                <td style="font-size: 13px; text-align: center; border:1px solid;">${row.name}</td>
                                <#list row.list?if_exists as el>
                                <td style="font-size: 13px; text-align: center; border:1px solid;">${el}</td>
                            </#list>
                        </#if>
                                
                    </tr>
                    <#if (sIndex % 23 == 0 && sIndex != 0)>
                        </table>
                        </div>
                        </div>
                        </section> 
                        <section class="sheet padding-standart landscape" style="position: relative;display: flex;justify-content: flex-start;">
                        <div style="display: flex; justify-content: center;">
                        <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                        <table style="width: 1094px;">
                    </#if>
               </#list>
            </table>
        </div>
      </div>
</section>

    <section class="sheet padding-standart landscape"
        style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
            <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: 18px;margin-left: -59px;">
                <h3
                    style="font-size: 15px; text-align: center; border:1px solid; font-weight: bold ; text-align: center;">
                    ТЎЛИҚ ҚУВВАТДА ИШЛАБ ЧИҚАРИШ ТАННАРХИ </h3>
                <table style="width: 1094px;">
                    <tbody>
                        <#list model.cost_productions?if_exists as cost>
                            <tr>
                                <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${cost.name} </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${cost.sum_value}  </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${cost.fixed_cost} </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${cost.dinamic_cost} </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${cost.fixed_value} </td>
                                <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${cost.dinamic_value} </td>
                            </tr>                        
                        </#list>
                        <tr>
                            <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"
                                colspan="6">Изоҳ. Ижтимоий суғурта ва бошқа ажратмалар ойлик иш ҳаққининг 8% ини ташкил
                                этади</td>
                        </tr>
                    </tbody>
                </table>



            </div>
        </div>
    </section>


    <section class="sheet padding-standart landscape" style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
              <div style="transform: rotate(-90deg);width: fit-content;max-height: 300px;position: absolute;bottom: 408px;left: -242px;">
                <table>
                 <tbody><tr> <td style="font-size: 15px; text-align: center; border:1px solid; font-weight: bold;" colspan="3232">МАҲСУЛОТ ТАННАРХИ, сўм</td> </tr>
                 <tr>
                    
                   <td colspan="2"></td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${index} - ${model.period_type}  </td>
                    </#list>
                 </tr>
                 <tr>
                   <td colspan="2"> Материал харажатлар </td>
                   <#list 1..model.period as index>
                    <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.sum_material_cost} </td>
                  </#list>
                 </tr>
                 <tr>
                   <td colspan="2"> Амортизация </td>
                   <#list 1..model.period as index>
                   <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.amart_sum} </td>
                 </#list>
                 </tr>
                 <tr>
                   <td colspan="2"> Ишчиларнинг и/х </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.sum_worker} </td>
                     </#list>
                 </tr> 
                 <tr>
                   <td colspan="2"> Ижтимоий суғурта тўлови </td>
                   <#list 1..model.period as index>
                   <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.sum_worker*0.12} </td>
                   </#list>
                 </tr> 
                     
                 <tr>
                   <td colspan="2" style="font-weight: bold;"> ФАБРИКА ТАННАРХИ</td>
                   <#list 1..model.period as index>
                       <td style="font-size: 13px; text-align: center; border:1px solid;">
                         ${model.sum_worker*0.12 + model.sum_worker + model.amart_sum + model.sum_material_cost} 
                        </td>
                    </#list>
                 </tr> 
    
                 <tr>
                   <td colspan="2"> Захира таннархи </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.sum_reserve} </td>
                     </#list>
                 </tr> 
    
                <tr>
                   <td colspan="2" style="font-weight: bold;"> СОТИЛАДИГАН МАХСУЛОТ ТАННАРХИ </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid;"> 
                        ${model.sum_worker*0.12 + model.sum_worker + model.amart_sum + model.sum_material_cost + model.sum_reserve} 
                     </td>
                     </#list>
                 </tr> 
    
                  <tr>
                   <td colspan="2"> Маъмурият иш хақи </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.sum_header} </td>
                    </#list>
                 </tr> 
    
                 <tr>
                   <td colspan="2"> Ижтимоий суғурта тўлови </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.sum_header*0.12}  </td>
                     </#list>
                 </tr> 
    
                 <tr>
                   <td colspan="2"> ИШЛАБ ЧИКАРИШ ТАННАРХИ </td>
                     <td style="font-size: 13px; text-align: center; border:1px solid;"> 
                        ${model.sum_worker*0.12 + model.sum_worker + model.amart_sum + model.sum_material_cost + model.sum_reserve + model.sum_header + model.sum_header*0.12}     
                    </td>
                 </tr>     
    
                 <tr>
                    <td colspan="2"> Амортизация </td>
                    <#list 1..model.period as index>
                    <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.amart_sum} </td>
                  </#list>
                  </tr>  
    
                 <tr>
                   <td colspan="2"> Кредит фоизи </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid;"> ${model.credit_schedule_year[index-1].sum_persent} </td>
                     </#list>
                 </tr>
    
                <tr>
                   <td colspan="2" style="font-weight: bold;"> ЖАМИ ИШЛАБ ЧИКАРИШ ТАННАРХИ </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">
                        ${model.sum_worker*0.12 + model.sum_worker + 2*model.amart_sum + model.sum_material_cost + 
                            model.sum_reserve + model.sum_header + model.sum_header*0.12 + model.credit_schedule_year[index-1].sum_persent}
                     </td>
                     </#list>
                 </tr>     
                 <tr>
                   <td colspan="2"> Сотиш харажатлари </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid;">
                        <#if index == 1> ${model.selling_ex} <#else> ${model.sum_material_cost*0.0001} </#if> </td> 
                     </#list>
                 </tr>
                 <tr>
                   <td colspan="2" style="font-weight: bold;"> СОТИЛГАН МАҲСУЛОТ ТАННАРХИ </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">
                        <#if index == 1> 
                        ${model.sum_worker*0.12 + model.sum_worker + 2*model.amart_sum + model.sum_material_cost + 
                            model.sum_reserve + model.sum_header + model.sum_header*0.12 + model.credit_schedule_year[index-1].sum_persent + model.selling_ex}
                        <#else> 
                        ${model.sum_worker*0.12 + model.sum_worker + 2*model.amart_sum + model.sum_material_cost + 
                            model.sum_reserve + model.sum_header + model.sum_header*0.12 + model.credit_schedule_year[index-1].sum_persent + model.sum_material_cost*0.0001}
                        </#if> </td> 
                     </#list>
                 </tr>       
    </tbody>
</table>             
            </div>
          </div>
    </section>


    <section class="sheet padding-standart" style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex;justify-content: start;gap: 24px;width: 100%;flex-direction: column;">
              <h3 style="font-size: 15px; text-align: center;font-weight: bold ; text-align: center;"> КРЕДИТНИ СУНДИРИШ ГРАФИГИ </h3>
                <table style="width: 100%;">
                  <tbody><tr>
                    <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;" colspan="3"> БАНК КРЕДИТИ </td>
                  </tr>
                      <tr>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Кредти муддати (ускуна) </td>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${model.credit_technique_month!"-"} </td>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ой </td>
                      </tr>
                      <tr>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Имтиёз даври (ускуна) </td>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${model.credit_technique_privilege_month!"-"} </td>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ой </td>
                      </tr>
                      <tr>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Кредти муддати (айланма маблағ) </td>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${model.credit_material_month! "-"} </td>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ой </td>
                      </tr>
                      <tr>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Имтиёз даври (айланма маблағ) </td>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${model.credit_material_privilege_month! "-"} </td>
                        <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ой </td>
                      </tr>
                  <tr>
                    <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Фоиз ставкаси </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> 18% </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> йиллик </td>
                  </tr> 
                  <tr>
                    <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Кредит суммаси </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${model.credit_sum} </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> сум </td>
                  </tr>               
                </tbody></table>
    
    <br>
          <br>
                <table style="width: 100%;">
                       <tbody><tr>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Давр </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Асосий карз тулови </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Хисобланган фоиз </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Жами тулов </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Кредит колдиги </td>
                        </tr>
                      <#list model.credit_schedule_year?if_exists as schedule>
                        <tr>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">${schedule.group_number} - йил</td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${schedule.sum_repayable} </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${schedule.sum_persent} </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${schedule.sum_total} </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${schedule.sum_residue} </td>
                        </tr>
                        </#list>
                </tbody></table>
          
            </div>
    </section>

    <section class="sheet padding-standart" style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex;justify-content: start;gap: 24px;width: 100%;flex-direction: column;">
                <table style="width: 100%;">
                       <tbody>
                        <tr>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Давр </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Асосий карз тулови </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Хисобланган фоиз </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Жами тулов </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> Кредит колдиги </td>
                        </tr>
                      <#list model.credit_schedule_month?if_exists as schedule_m>
                      <#assign schindex=schedule_m?index + 1>
                        <tr>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;">${schedule_m.number} - ой</td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${schedule_m.repayable} </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${schedule_m.percent_sum} </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${schedule_m.payment} </td>
                          <td style="font-size: 13px; text-align: center; border:1px solid; font-weight: bold;"> ${schedule_m.residue} </td>
                        </tr>
                        <#if schindex%36 == 1 && schindex != 1>
                    </tbody>
                </table>
                </div>
        </section>
        <section class="sheet padding-standart" style="position: relative;display: flex;justify-content: flex-start;">
            <div style="display: flex;justify-content: start;gap: 24px;width: 100%;flex-direction: column;">
                    <table style="width: 100%;">
                        </#if>
                        </#list>
                </tbody>
            </table>
            </div>
    </section>

    <section class="sheet padding-standart landscape" style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex; justify-content: center;">
              <div style="transform: rotate(-90deg);width: fit-content;margin-bottom: -8px;margin-left: 186px;">
                <table style="width: 100%;">
                  <tbody><tr> <td colspan="342342" style="font-weight:bold"> Ишчи капитал бўйича таклифлар сум</td> </tr>
                  <tr> 
                    <td colspan="1"></td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1">Қамров кунлари</td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="2">Айланма коэффициенти <br> (360 / Қамров кунлари) </td>
                  </tr>
                  <tr> 
                    <td colspan="1">Маҳсулот ишлаб чиқиш учун тушум даври</td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> ${model.other_costs.productSales} кун</td>
                    <#if model.other_costs.productSales != 0>
                      <td style="font-size: 13px; text-align: center; border:1px solid;" colspan="1">
                            ${360 / model.other_costs.productSales}
                        </td>
                    <#else>
                        <td style="font-size: 13px; text-align: center; border:1px solid;" colspan="1">
                            -
                        </td>
                    </#if>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1">Дебитор қарздорлик = Умумий сотувлар / Коэффициент </td>
                  </tr>
                  <tr> 
                    <td colspan="1">Омбордаги хомашё захира даври</td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> ${model.other_costs.materialWarehouse} кун</td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> 
                        <#if model.other_costs.productSales != 0> ${360/model.other_costs.materialWarehouse} <#else> - </#if>
                    </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> Тайёр маҳсулот заҳиралари = Маҳсулот нарҳи / Айланма </td>
                  </tr>
                  <tr> 
                    <td colspan="1">Тайёр маҳсулот сақланиш даври</td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> ${model.other_costs.materialStorage} кун</td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1">
                        <#if model.other_costs.materialStorage != 0> ${360/model.other_costs.materialStorage} <#else> - </#if>
                    </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1">Тайёр маҳсулот заҳиралари = Маҳсулот нарҳи / Айланма коэффициенти </td>
                  </tr>
                  <tr> 
                    <td colspan="1"> Эхтиёт қисмлар заҳиралари </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> ${model.other_costs.partStorage} кун</td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1">
                        <#if model.other_costs.partStorage != 0> ${360/model.other_costs.partStorage} <#else> - </#if>
                    </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1">Эхтиёт қисмлар заҳиралари = Ҳом-ашё / Айланма коэффициенти </td>
                  </tr>
                  <tr> 
                    <td colspan="1"> Хомашё етказиб берувчиларга тўлов даври </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> ${model.other_costs.paymentPeriod} кун</td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> 
                        <#if model.other_costs.paymentPeriod != 0> ${360/model.other_costs.paymentPeriod} <#else> - </#if>
                    </td>
                    <td style="font-size: 13px; text-align: center; border:1px solid; " colspan="1"> Кредитор қарздорлиги = Ҳом-ашё / Айланма коэффициенти</td>
                  </tr>
                </tbody></table>
    <br>
              <br>
          <table style="width: 100%;">
            <tbody><tr><td style="font-weight: bold;" colspan="342"> ТОЗА ИШЧИ КАПИТАЛ ЮЗАСИДАН ТАКЛИФЛАР </td></tr>
                 <tr>
                   <td></td>
                   <td> Инвестиции </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; "> ${index} - йил  </td>
                     </#list>
                 </tr>
                 <tr>
                 </tr>
                 <tr>
                    <td> Задолженность </td>
                    <td style="text-align: center;font-size: 13px"> 0 </td>
                    <#list 1..model.period as index>
                      <td style="font-size: 13px; text-align: center; border:1px solid; "> ${model.selling_ex*model.other_costs.productSales/360}  </td>
                      </#list>
                  </tr>                  
                 <tr>
                   <td>Запасы сырья</td>
                   <td style="text-align: center;font-size: 13px"> 0 </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; "> ${model.sum_material_cost*model.other_costs.materialWarehouse/360}  </td>
                     </#list>
                 </tr>  
                 <tr>
                   <td>Запасы готовой продукции</td>
                   <td style="text-align: center;font-size: 13px"> 0 </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; "> ${model.sum_reserve*model.other_costs.materialStorage/360} </td>
                     </#list>
                 </tr> 
                <tr>
                   <td>ВСЕГО</td>
                   <td style="text-align: center;font-size: 13px"> 0 </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; "> 
                        ${model.selling_ex*model.other_costs.productSales/360 + model.sum_material_cost*model.other_costs.materialWarehouse/360 + 
                            model.sum_reserve*model.other_costs.materialStorage/360}
                    </td>
                    </#list>
                 </tr>
                <tr>
                   <td>Кредиторская задолженность</td>
                   <td style="text-align: center;font-size: 13px"> 0 </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; "> ${model.sum_material_cost*model.other_costs.paymentPeriod/360}  </td>
                     </#list>
                 </tr>
                <tr>
                   <td> Тоза ишчи капитал </td>
                   <td style="text-align: center;font-size: 13px"> 0 </td>
                   <#list 1..model.period as index>
                     <td style="font-size: 13px; text-align: center; border:1px solid; ">
                        ${model.selling_ex*model.other_costs.productSales/360 + model.sum_material_cost*model.other_costs.materialWarehouse/360 + 
                            model.sum_reserve*model.other_costs.materialStorage/360 - model.sum_material_cost*model.other_costs.paymentPeriod/360}    
                    </td>
                     </#list>
                 </tr>
                 <tr>
                   <td>Ишчи капиталдаги ўзгаришлар</td>
                   <td style="text-align: center;font-size: 13px"> 0 </td>
                   <#list 1..model.period as index>
                        <td style="font-size: 13px; text-align: center; border:1px solid; "> 
                         <#if index == 1> 
                         ${model.selling_ex*model.other_costs.productSales/360 + model.sum_material_cost*model.other_costs.materialWarehouse/360 + 
                            model.sum_reserve*model.other_costs.materialStorage/360 - model.sum_material_cost*model.other_costs.paymentPeriod/360} 
                            <#else>
                            0
                         </#if>    
                        </td>

                    </#list>
                     
                 </tr>
          </tbody></table>
                       </div>
            </div>
    </section>

    <section class="sheet padding-standart landscape" style="position: relative;display: flex;justify-content: flex-start;">
        <div style="display: flex;justify-content: center;transform: rotate(-90deg);width: fit-content;min-width: 1048px;">
          <table style="width: 100%;height: 596px;">
              <tbody><tr><td style="font-weight: bold;" colspan="342"> ПРОГНОЗ ФОЙДА ВА ЗАРАР </td></tr>
              <tr>
                  <td colspan="2"></td>
                  <#list 1..model.period as index>
                    <td style="font-size: 13px; text-align: center; border:1px solid; "> ${index} - йил  </td>
                  </#list>
              </tr>
              <#list model.profit_loss?if_exists as pr_ls>
                      <#assign schindex=pr_ls?index + 1>
              <tr>
                  <td colspan="2">${pr_ls.name}</td>
                  <#if pr_ls.type == 0>
                    <#list 1..model.period as index>
                    <td style="font-size: 13px; text-align: center; border:1px solid;" <#if pr_ls.color?has_content && pr_ls.color == 'black'> class="bold_color"</#if>> ${pr_ls.value} </td>
                    </#list>
                  </#if>
                  <#if pr_ls.type == 1>
                  <#list 1..model.period as index>
                    <td style="font-size: 13px; text-align: center; border:1px solid;" <#if pr_ls.color?has_content && pr_ls.color == 'black'> class="bold_color"</#if>> 
                        ${model.credit_schedule_year[index-1].percent_sum! 0}
                     </td>
                    </#list>
                  </#if>
              </tr>
              </#list>
  </tbody></table>
  </div>
  </section>

    <section class="sheet padding-standart" style="text-align: center">
        <tr valign="top">
            <th valign="top" align="left" width="84px;">
                <img id="doc_qr_code" style="height:80px;width:80px;"
                    src="data:image/jpeg;base64, ${global.documentQrcodeBase64}" alt="QR-code">
            </th>
        <tr>
            <td colspan="3" style="font-weight: normal;">
                <div align="left"><i>${(global.documentUrl)!"-"}</i></div>
            </td>
        </tr>
        </tr>
        </table>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript"></script>
</body>

</html>