<!DOCTYpE html>
<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Кредит шартномаси</title>
	<style type="text/css">
		html {
			line-height: 1.15;
			-ms-text-size-adjust: 100%;
			-webkit-text-size-adjust: 100%
		}

		article,
		aside,
		footer,
		header,
		nav,
		section {
			display: block
		}

		h1 {
			font-size: 24px
		}

		h2 {
			font-size: 20px
		}

		.m-5 {
			margin-top: 5px;
		}

		@page {
			margin: 0
		}

		body {
			margin: 0
		}

		.sheet {
			margin: 0;
			overflow: hidden;
			position: relative;
			box-sizing: border-box;
			page-break-after: always
		}

		.landscape-page {
			overflow: hidden;
			position: relative;
			box-sizing: border-box;
			page-break-after: always;
			width: 296mm;
			height: 210mm;
			margin: 0 auto;
		}

		body.A3 .sheet {
			width: 297mm;
			height: 419mm;
			margin-left: auto;
			margin-right: auto
		}

		body.A3 .landscape.sheet {
			width: 420mm;
			height: 296mm;
			margin-left: auto;
			margin-right: auto
		}

		body.A4 .sheet,
		body.A4 .landscape.sheet {
			width: 210mm;
			height: 296mm;
			margin-left: auto;
			margin-right: auto
		}

		body.A4 .landscape.sheet {
			margin-top: -160px;
			margin-bottom: -160px;
			-webkit-transform: rotate(90deg);
			-moz-transform: rotate(90deg);
			-o-transform: rotate(90deg);
			-ms-transform: rotate(90deg);
			transform: rotate(90deg)
		}

		body.A4 .landscape.sheet .content {
			width: 278mm;
			height: 209mm;
			margin: 105px 0 0 -100px;
			-webkit-transform: rotate(-90deg);
			-moz-transform: rotate(-90deg);
			-o-transform: rotate(-90deg);
			-ms-transform: rotate(-90deg);
			transform: rotate(-90deg)
		}

		body.A5 .sheet {
			width: 148mm;
			height: 209mm;
			margin-left: auto;
			margin-right: auto
		}

		body.A5 .landscape.sheet {
			width: 210mm;
			height: 147mm;
			margin-left: auto;
			margin-right: auto
		}

		.landscape.sheet.padding-standart {
			padding: 15mm 10mm 10mm 10mm;
		}

		.sheet.padding-standart {
			padding: 15mm 15mm 20mm 30mm;
		}

		.sheet.padding-10mm {
			padding: 10mm
		}

		.sheet.padding-15mm {
			padding: 15mm
		}

		.sheet.padding-20mm {
			padding: 20mm
		}

		.sheet.padding-25mm {
			padding: 25mm
		}

		.sheet.continuous {
			margin: 0
		}

		@media screen {
			body {
				background: #e0e0e0
			}

			.sheet {
				background: white;
				box-shadow: 0 .5mm 2mm rgba(0, 0, 0, .3);
				margin: 5mm
			}

			.landscape-page {
				background: white;
				box-shadow: 0 .5mm 2mm rgba(0, 0, 0, .3);
				/*margin:5mm*/
			}
		}

		@media print {
			body.A3 .landscape {
				width: 420mm;
			}

			body.A3 {
				width: 297mm;
			}

			body.A4 .landscape.sheet {
				margin-top: auto;
				margin-bottom: auto;
				-webkit-transform: rotate(0deg);
				-moz-transform: rotate(0deg);
				-o-transform: rotate(0deg);
				-ms-transform: rotate(0deg);
				transform: rotate(0deg)
			}

			body.A4,
			body.A5 .landscape {
				width: 210mm
			}

			body.A5 {
				width: 148mm
			}

			.landscape-page {
				width: 296mm;
			}

		}

		@media print {

			body,
			page {
				margin: 0;
				box-shadow: 0 0 0 rgba(0, 0, 0, 0);
			}

			@page {
				size: A4;
				margin: 0;
			}
		}

		* {
			margin: 0;
			padding: 0;
			font-size: 14px;
			line-height: 18px
		}

		body {
			background: rgb(204, 204, 204);
		}

		page {
			background: white;
			display: block;
			margin: 0.5cm;
			box-shadow: 0 0 0.5cm rgba(0, 0, 0, 0.5);
		}

		page[size="A4"] {
			width: 21cm;
			height: 29.7cm;
		}

		table {
			border-collapse: collapse;
			border: 0px solid #000;
			margin: 4px 0 0 0;
			width: 100%;
			line-height: 1.15
		}

		.landscape.sheet table th {
			padding: 0px;
			font-size: 12px
		}

		.landscape.sheet table td {
			padding: 1px 5px;
			font-size: 12px;
			text-indent: 0px
		}

		.sheet table th {
			padding: 4px 2px;
			font-size: 14px
		}

		.sheet table td {
			padding: 2px 2px 2px 2px;
			font-size: 14px;
			text-indent: 0px
		}

		table.clean th {
			padding: 2px 6px;
			font-size: 12px;
			text-indent: 0px;
			font-weight: normal
		}

		.page_number {
			position: absolute;
			margin-left: auto;
			margin-right: auto;
			left: 0;
			right: 0;
			text-align: center;
			bottom: 15px;
			font-family: Calibri;
			font-size: 12pt
		}

		p {
			text-indent: 40px;
			margin: 0;
			font-size: 14px;
		}

		.noTextIndent {
			text-indent: 0px;
		}

		thead tr th,
		tbody tr th,
		tbody tr td {
			text-align: center;
		}

		.part11t {
			border: 1px solid black;
		}

		br {
			line-height: 1em;
		}

		.h4,
		.h5,
		.h6,
		h4,
		h5,
		h6 {
			margin-top: 10px !important;
			margin-bottom: 10px !important;
			font-size: 16px !important
		}

		.verticalTableHeader {
			text-align: center;
			white-space: nowrap;
			transform-origin: 50% 50%;
			transform: rotate(-90deg);
		}
	</style>
</head>

<body class="A4">
	<#setting number_format="0">
		<section class="sheet padding-standart">
			<div >
				<br>
				<div class="part1" style="text-align: center; font-size: 15px; font-weight: 700;">
					 KREDIT LINIYASI OCHMASDAN KREDIT BERISH SHARTNOMASI  № ${model.doc_num!"_________________"} 
				</div>
				<br>
				<div class="part2" style="display: flex;">
					<div class="part2_1" style=" width: 50%; ">
						${model.district!"_________________ ш."}
					</div>
					<div class="part2_2" style=" width: 50%; text-align: right;">
						${model.doc_date!"_________________"} йил
					</div>
				</div>
				<br>
				<p>
					Bundan buyon shartnoma matnida “Bank” deb yuritiluvchi “Mikrokreditbank” ATB nomidan Nizom hamda Ishonchnoma asosida ish yurituvchi 
                     ${model.branch_name!"_________________"} boshqaruvchisi ${model.branch_header!"_________________"} bir tomondan hamda bundan buyon matnda “Qarz oluvchi” deb yuritiluvchi 
                    <#if model.sender_type == 'yuridik shaxs'>
                        ${model.sender_type!"_________________"} ${model.sender_name!"_________________"} nomidan ${model.director_name!"_________________"} 
                    <#else>
                    ${model.sender_type!"_________________"} ${model.sender_name!"_________________"} 
                    </#if>
                    ikkinchi tomondan birgalikda “Tomonlar” quyidagilar haqida shartnoma tuzdilar:

				</p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>1.	SHARTNOMA PREDMETI</p>
				</div>
				<p>
					1.1.	Bank Qarz oluvchiga mazkur shartnomada koʻrsatib oʻtilgan miqdorda va shartlar asosida pul mablagʻlari (kredit) berish majburiyatini, Qarz oluvchi esa oʻz navbatida, olingan pul mablagʻlarini belgilangan muddatda qaytarish va pul mablagʻlaridan foydalanganligi uchun foizlar toʻlash majburiyatini oladi.
				</p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>2.	KREDITNING SHARTLARI</p>
				</div>
				<p>
					2.1.	Kredit summasi:
                     <#if model.credit_material_sum ?? && model.credit_material_sum != "0">
						- xom-ashyo, aylanma mablag': ${model.credit_material_sum!"0"} (${model.credit_material_sum_word!"____________"})
                      </#if>
						- asosiy vosita: ${model.credit_technique_sum!"0"} (${model.credit_technique_sum_word!"_______"}) soʻm.
				</p>
                <p>
                    2.2.	Kreditdan foydalanish muddati <br>
                    <#if model.credit_material_sum ?? && model.credit_material_sum != "0">
                        - xom-ashyo, aylanma mablag': ${model.credit_mat_month!"____________"} oy (shu jumladan, imtiyozli davr  ${model.credit_mat_priv_month!"____________"} oy).
                    </#if>
		    			- asosiy vosita: ${model.credit_tech_month!"____________"} oy (shu jumladan, imtiyozli davr ${model.credit_tech_priv_month!"____________"} oy)
                </p>
                <p>
                    2.3.	Kredit boʻyicha asosiy qarz va foizlar ushbu shartnomaning 1-sonli ilovasida koʻrsatilgan jadvalga asosan differensial toʻlov usulida toʻlanadi.
                </p>
                <p>
                    2.4.	Kredit boʻyicha foiz stavkasi yillik 18(o'n sakkiz) %.
                </p>
                <p>
                    2.5.	Kreditdan foydalanganlik uchun foiz stavkasi turi oʻzgarmas.
                </p>
                <p>
                    2.6.	Foizlarni toʻlash muddati: har oyning  5-sanasiga qadar.
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>3.	QARZ OLUVCHINING TASDIGʻI</p>
				</div>
				<p>
					3.1.	Qarz oluvchi quyidagilarni tasdiqlaydi va kafolatlaydi:
				</p>
                <p>
                    - Oʻzbekiston Respublikasining amaldagi qonun hujjatlariga asosan tashkil qilingan va roʻyxatdan oʻtkazilgan yuridik shaxs/Yakka tartibdagi tadbirkor hisoblanadi hamda shartnomani tuzish va uni bajarish uchun huquqiy layoqatga ega;
                </p>
                <p>
                    - ushbu shartnomani tuzish va uni ijro qilish hamda shartnomaning barcha shartlari qarz oluvchining taʼsis hujjatlariga zid emas;
                </p>
                <p>
                    - kredit olish va uni rasmiylashtirish uchun Bankka taqdim etilgan/etiladigan barcha hujjat hamda maʼlumotlar asl va haqiqiy;
                </p>
                <p>
                    - bankka taqdim etilgan moliyaviy hisobotlar haqiqiy va ular qarz oluvchining haqiqiy moliyaviy ahvolini aks ettiradi. Qarz oluvchi Bankka taqdim etgan moliyaviy hisobot va boshqa hujjatlarda aks ettirilgan majburiyatlardan boshqa haqiqiy yoki shartli majburiyatlarga, shuningdek, boshqa shaxslar foydasiga berilgan kafillikka ega emas;
                </p>
                <p>
                    - qarz oluvchiga nisbatan maʼmuriy, arbitraj va sud ishlari qoʻzgʻatilmagan, uchinchi shaxslar oldida  mazkur shartnoma boʻyicha majburiyatlarini bajarishiga sezilarli darajada taʼsir koʻrsatishi mumkin boʻlgan bajarilmagan majburiyatlari yoʻq;
                </p>
                <p>
                    - qarz oluvchi unga Bank tomonidan ajratilayotgan kredit toʻgʻrisidagi maʼlumotlarni Kredit axborotining davlat reestri va kredit byurosiga taqdim etilishiga oʻz roziligini bergan;
                </p>
                <p>
                    - xorijiy valyuta kursining oʻzgarishi natijasida xorijiy valyutada olingan kredit boʻyicha milliy valyutadagi qarz yukining oshishi bilan bogʻliq ravishda kelib chiqadigan oqibatlar uning tavakkalchiligi hisoblanadi.
                </p>
                <p>
                   - qarz oluvchi ushbu kredit mablagʻini olishda oʻzining yoki boshqa shaxslarning jinoiy faoliyatidan olingan daromadlarini legallashtirish maqsadini koʻzlamagan;
                </p>
                <p>
                    - qarz oluvchi oʻzi va taʼsischilari toʻgʻrisidagi maʼlumotlar “Bank siri toʻgʻrisida”gi va “Jinoiy faoliyatdan olingan daromadlarni legallashtirishga va terrorizmni moliyalashtirishga qarshi kurashish toʻgʻrisida”gi Oʻzbekiston Respublikasining qonunlariga muvofiq, bank tomonidan belgilangan tartibda vakolatli davlat organlariga taqdim etilishidan xabardor;
                </p>
		</section>

		<section class="sheet padding-standart">	
                <p>
                    - kreditni qaytarish jadvali boʻyicha muddatida toʻlanmagan asosiy qarz va unga hisoblangan foizlarni Qarz oluvchining hisobvaragʻidan akseptsiz yechib olinishidan xabardor va ushbu shartnomani tasdiqlash (imzolash) orqali akseptsiz yechib olinishiga 
oʻz roziligini bergan hisoblanadi.
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>4.	TARAFLARNING HUQUQ VA MAJBURIYATLARI</p>
				</div>
				<p>
					4.1.	Bankning majburiyatlari:
				</p>
                <p>
                    4.1.1.	Qarz oluvchiga mazkur shartnomada belgilangan miqdorda va shartlarda kredit ajratish.
                </p>
                <p>
                    4.1.2.	 Olingan kreditni hisoblash uchun qarz oluvchiga ssuda hisobvaragʻini ochish.
                </p>
                <p>
                    4.1.3.	 Qarz oluvchini Bank tomonidan kreditni muddatidan ilgari undirish faktlari va sabablari haqida xabardor qilish.
                </p>
                <p>
                    4.1.4.	 Bank Qarz oluvchiga kreditni berishdan butunlay yoki qisman bosh tortgan taqdirda, ushbu kreditni ajratishni toʻxtatib qoʻyish toʻgʻrisida qaror qabul qilingan sanadan boshlab keyingi ish kunidan kechiktirmasdan Qarz oluvchiga sababi yuzasidan yozma xabarnoma yuborish;
                </p>
                <p>
                    4.1.5.	Xoʻjalik yurituvchi subyektlarni kreditlash boʻyicha qonunchilikka kiritiladigan oʻzgartirishlar kredit shartnomasining tegishli bandlari oʻzgartirilishiga olib kelgan taqdirda bu haqda Qarz oluvchiga xabar berish va shartnomaga qoʻshimcha hamda oʻzgartirishlar kiritish choralarini koʻrish;
                </p>
                <p>
                    4.1.6. Kredit shartnomasi boʻyicha muddati oʻtkazib yuborilgan qarzdorlik yuzaga kelganda, bank Qarz oluvchiga muddati oʻtkazib yuborilgan qarzdorlik yuzaga kelgan sanadan boshlab 7 (yetti) kalendar kuni davomida xabardor qilish;
                </p>
                <p>
                    4.1.7. Qarz oluvchi bilan shartnomada kelishilgan har qanday aloqa bogʻlash usullaridan, shu jumladan, elektron aloqa vositalaridan yoki qonun hujjatlarida nazarda tutilgan boshqa usullardan foydalanib, Qarz oluvchiga muddati oʻtkazib yuborilgan qarzdorlik yuzaga kelganligi haqida soʻndirish jadvalini ilova qilgan holda xabar berish;
                </p>
                <p>
                   4.1.8.	 Bank Qarz oluvchi tomonidan shartnomaga asosan kredit boʻyicha qarzdorlik summasini toʻlash majburiyati toʻliq bajarilgan sanadan boshlab uch ish kunidan kechiktirmagan holda mazkur qarz boʻyicha garovda turgan mulkni taqiqdan chiqarish, garov sifatida boʻlgan mol-mulkka nisbatan bankning huquqlari toʻgʻrisidagi yozuvni garov reestridan chiqarish choralarini koʻrish;
                </p>
                <p>
                    4.1.9. Bank tomonidan kredit boʻyicha qarzdorliklarni soʻndirish uchun Qarz oluvchining barcha bank hisobvaraqlaridan Qarz oluvchining topshirigʻisiz hisobdan chiqarilganda, bank ushbu mablagʻ hisobdan chiqarilgan sanadan boshlab keyingi ish kunidan kechiktirmagan holda Qarz oluvchiga uning sabablarini koʻrsatgan holda shaxsan, pochta yoki elektron aloqa vositalari va boshqa kommunikatsiya kanallari orqali xabarnoma joʻnatish tartibiga amal qilish.
                </p>
                <p>
                    4.2.	Qarz oluvchining majburiyatlari:
                </p>
                <p>
                    4.2.1.	 Kreditni va u boʻyicha hisoblangan foizlarni mazkur shartnomada belgilangan muddatlarda va miqdorda toʻliq qaytarish.
                </p>
                <p>
                    4.2.2.	 Kreditdan faqat mazkur shartnomada koʻrsatib oʻtilgan maqsadlarda foydalanish.
                </p>
                <p>
                    4.2.3.	 Kreditdan foydalanish davrida kreditlashning qaytarishlik, toʻlovlilik, taʼminlanganlik, muddatlilik va maqsadli foydalanish tamoyillariga rioya qilish.
                </p>
                <p>
                    4.2.4.	 Qarz oluvchining moliyaviy ahvolini monitoring va tahlil qilish uchun Bankka har oyda buxgalterlik balanslari, foyda va zararlar boʻyicha moliyaviy hisobotlar hamda boshqa hujjatlar va maʼlumotlarni taqdim etish.
                </p>
                <p>
                    4.2.5.   Bank xodimlarining maqsadli tekshirishlar (qarz oluvchining moliyaviy holati, hisob yuritish hamda hisobot berish ahvoli, kreditdan maqsadli foydalanish, kreditlangan tovar-moddiy boyliklarning hamda garovga qoʻyilgan mulkning saqlanish va butligi masalalari boʻyicha) oʻtkazishlari uchun ishlab chiqarish, ombor, xizmat va boshqa binolarga kiritish, shuningdek, ularning talablariga asosan birlamchi hisobot va buxgalterlik hujjatlari bilan tanishtirish.
                </p>
                <p>
                   Maqsadli tekshirishlarni oʻtkazish muddati Bank tomonidan belgilanadi.
                </p>
                <p>
                    4.2.6.	Tashkiliy-huquqiy shaklining oʻzgarishi yoki qarz oluvchining moliyaviy ahvoliga oʻz taʼsirini oʻtkazuvchi har qanday boshqa qayta tashkil etish holatlari haqida Bankni oldindan (15 kun avval) yozma ravishda xabardor qilish.
                </p>
                <p>
                    4.2.7.	 Qayta tashkil etilayotganda (huquqiy voris boʻlgan hollar bundan mustasno) yoki tugatilayotganda zudlik bilan kreditni muddatidan oldin qaytarish hamda hisoblangan barcha foizlarni toʻlash.
                </p>
                <p>
                    4.2.8.	 Mazkur shartnoma amal qilish muddati davomida qarz oluvchi quyidagilarning bajarilishini taʼminlashi lozim:
                </p>
                <p>
                    - oʻz faoliyatini malakali rahbarlar nazorati ostida, lozim darajadagi samaradorlik bilan qonunchilikka muvofiq, shuningdek, umum tan olingan tamoyillar va sogʻlom amaliyotga asoslanib amalga oshirish (faoliyat yuritish);
                </p>
		</section>

		<section class="sheet padding-standart">	
                <p>
                    - oʻz mulkini, asbob-uskunalari va boshqa mol-mulkini normal ahvolda saqlash (asosiy fondlarni ekspluatatsiya qilish);
                </p>
                <p>
                    - buxgalterlik hisobini va ichki nazoratni amaldagi buxgalterlik hisobi va hisoboti qoidalariga asosan olib borish hamda har yili oʻz moliyaviy hisobotlarining auditini oʻtkazish;
                </p>
                <p>
                   - agar Bank boshqa shartlarga rozi boʻlmasa, aylanma mablagʻlari belgilangan meʼyor (normativ)dan, shuningdek, boshqa koeffitsiyentlarni (qaytarish, likvidlik va boshqalar) kredit berish vaqtida qayd etilgan darajadan past boʻlmagan holda boʻlishini taʼminlash;
                </p>
                <p>
                    - kreditlanayotgan loyihani lozim darajadagi samaradorlik bilan xavfsizlik, atrof-muhitni muhofaza qilish normalari va amaliyotiga asosan amalga oshirish;
                </p>
                <p>
                    - har qanday sud nizolari, shartnomaviy majburiyatlardagi yoki uning moliyaviy holati boʻyicha kreditning qaytarilishiga salbiy taʼsir koʻrsatuvchi boshqa oʻzgarishlardan Bankni xabardor qilib turish;
                </p>
                <p>
                    - oʻzining faoliyatini amalga oshirish va mazkur shartnoma shartlarini bajarish uchun lozim boʻlgan barcha ruxsat va litsenziyalarni oʻz vaqtida olish hamda ularning muddatini uzaytirish.
                </p>
                <p>
                    4.2.9.	 Oʻzbekiston Respublikasi Fuqarolik kodeksining 776- va 
783-moddalariga asosan, Bankning birinchi talabi bilan mazkur talabni qondirish uchun yetarli boʻlgan pul mablagʻlarini oʻzining barcha hisobvaragʻlaridan Bank hisobvaragʻiga oʻtkazish toʻgʻrisida oʻziga xizmat koʻrsatuvchi bankka topshiriq berish.
                </p>
                <p>
                    4.3.	Bankning huquqlari:
                </p>
                <p>
                    4.3.1.	 Qarz oluvchi toʻlovga layoqatsiz deb topilganda, kreditni taʼminlash boʻyicha oʻz majburiyatlarini bajarmaganda, kreditdan maqsadsiz foydalanganda, taqdim etilgan kreditning qaytarilishiga taʼsir koʻrsatuvchi maʼlumot va hisobotlarning haqqoniy emasligi shartnoma imzolangandan keyin aniqlanganda hamda Qarz oluvchi tomonidan Bankning ushbu shartnoma boʻyicha majburiyatlari kuchga kirgan vaqtdan boshlab 1 oydan koʻp muddat davomida kreditdan foydalanilmaganda (toʻlov hujjatlarini taqdim etmaslik) ushbu shartnomada nazarda tutilgan kreditni berishdan butunlay yoki qisman bosh tortish.
                </p>
                <p>
                    4.3.2.	 Kreditlash jarayonida ajratilgan kreditga tegishli boʻlgan buxgalteriya va statistik hisobotlarni (korxonaning moliyaviy-xoʻjalik ahvoli, kreditdan maqsadli foydalanish, kreditning taʼminlanganligi, kreditga layoqatliligi va boshqalar) olish va tahlil qilish.
                </p>
                <p>
                    4.3.3.	 Quyidagi hollarda qarz oluvchini bundan buyon kreditlashni toʻxtatish va foizlarni hamda kredit boʻyicha asosiy qarzni muddatidan oldin, shuningdek, undiruvni kredit taʼminotiga qaratish orqali undirish:
                </p>
                <p>
                    - kredit mablagʻlaridan maqsadsiz foydalanilganligi aniqlanganda;
                </p>
                <p>
                    - qarz oluvchi  tomonidan mazkur kredit shartnomasida belgilangan har qanday toʻlov majburiyatlari bajarilmagan hollarda;
                </p>
                <p>
                    - qarz oluvchining moliyaviy ahvoli yomonlashganda (zararlar, nolikvid balans va boshqalar) buxgalterlik hisobi lozim darajada yuritilmaganda, taqdim etilgan hisobotlarning notoʻgʻriligi (haqqoniy emasligi) aniqlanganda;
                </p>
                <p>
                    - ajratilgan kreditning qaytarilishi turli sabablarga koʻra  taʼminlanmagan boʻlib qolgan hollarda yoki Bank xulosasiga koʻra taqdim etilgan taʼminot toʻliq yoki qisman oʻz qiymatini yoʻqotgan yoki haqiqiy emas deb topilganda;
                </p>
                <p>
                    - kredit qaytarilishiga salbiy taʼsir koʻrsatuvchi mazkur shartnomada koʻzda tutilgan boshqa majburiyatlar bajarilmaganda;
                </p>
                <p>
                    - mazkur shartnoma bilan bogʻliq boʻlgan boshqa shartnoma (garov, kafolat, sugʻurta va b.) shartlari bajarilmaganda yoki buzilganda.
                </p>
                <p>
                    Bunday hollarda Bank oldindan ___ kundan koʻp boʻlmagan muddat ichida qarz oluvchini xabardor qiladi, ammo qarz oluvchini Bank tomonidan ogohlantirilmaganligi Bankning bundan buyon kreditlashni toʻxtatish va foizlarni hamda kredit boʻyicha asosiy qarzni muddatidan oldin undirishga boʻlgan huquqiga oʻz taʼsirini koʻrsatmaydi.
                </p>
                <p>
                    4.3.4.	 Bevosita qarz oluvchi joylashgan yerda maqsadli tekshirishlarni amalga oshirish.
                </p>
                <p>
                    4.3.5.	 Qarz oluvchining kredit tarixini shakllantirish uchun zarur boʻlgan maʼlumotlarni Kredit axborot tahlil markazi va Kredit axborot milliy institutilariga taqdim etish.
                </p>
                <p>
                    4.3.6.	 Mazkur Shartnoma boʻyicha Bank oʻzining qonuniy talablarini qanoatlantirish uchun zarur boʻlgan tegishli pul mablagʻlarini Oʻzbekiston Respublikasi Fuqarolik kodeksining 783-moddasiga muvofiq, Qarz oluvchining barcha hisobvaragʻlaridan uning topshirigʻisiz soʻzsiz (akseptsiz) tartibda toʻlov talabnomasi yoki memorial order orqali koʻchirib (undirib) olish.
                </p>
                <p>
                    4.3.7.	 Kreditlash jarayoni bank komplaens nazorat xodimi oʻzaro aloqadorlik yohud boshqa omillar taʼsirida kreditdan maqsadsiz va samarasiz foydalanish natijasida kreditning qaytmaslik xatari yoki boshqa tavakkalchiliklarning yuzaga kelish ehtimoli yuqori boʻlgan sohalar doirasida tegishli oʻrganishlar oʻtkazish
                  
		</section>

		<section class="sheet padding-standart">	
                huquqiga ega. Komplaens nazorat xodimi oʻrganishlari doirasida aniqlangan qoidabuzarliklar yuzasidan tayyorlangan yozma xulosasi boʻyicha tegishli kollegial organning qaroriga asosan, kreditlashning istalgan bosqichida, jumladan, kredit shartnomasi va taʼminot hujjatlari rasmiylashtirilgandan soʻng ham toʻxtatilishi yoki moliyalashtirish butunlay rad etilishi mumkin.
                </p>
                <p>
                    4.3.8.	 Qarz oluvchiga ajratilgan kreditlar boʻyicha muddati oʻtgan asosiy yoki foiz qarzdorligi yuzaga kelgan shartnoma boʻyicha ajratilmasdan turgan bank majburiyati bank tomonidan bir tomonlama bekor qilinishi mumkin.
                </p>
                <p>
                    4.4.	Qarz oluvchining huquqlari:
                </p>
                <p>
                    4.4.1.	 Kredit mablagʻlari ajratilguniga qadar kredit olishdan bepul asosda voz kechish;
                </p>
                <p>
                    4.4.2.	 Kredit mablagʻlarini  muddatidan oldin qaytarish.
                </p>
                <p>
                    4.4.3.	 Kredit qarzorliklari boʻyicha Bankdan maʼlumotlar olish;
                </p>
                <p>
                    4.4.4.	 Kreditlash va hisob-kitoblar boʻyicha Oʻzbekiston Respublikasi meʼyoriy-huquqiy hujjatlari va Bankning ichki meʼyoriy hujjatlaridagi oʻzgarishlar haqida Bankdan maʼlumot olish.
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>5.	HISOB-KITOBLAR TARTIBI VA SHARTNOMA BAHOSI</p>
				</div>
				<p>
					5.1.	Bankning kredit ajratish yuzasidan majburiyati vujudga kelganidan keyin Qarz oluvchining toʻlov hujjatiga asosan, Bank kreditni mazkur shartnomada koʻrsatilgan shartlar asosida Qarz oluvchining ssuda hisobvaragʻidan pul oʻtkazish yoʻli bilan ajratadi.
				</p>
                <p>
                    5.2.	Qarz oluvchi berilgan kredit uchun foizlarni Bankka mazkur shartnomada belgilangan muddatda va miqdorda Bank amalga oshirgan hisob-kitob asosida toʻlaydi.
                </p>
                <p>
                    5.3.	Kreditdan foydalanganlik uchun foizlar har kuni Bank tomonidan hisoblab boriladi.
                </p>
                <p>
                    5.4.	Qabul qilingan muddatli majburiyatnomalar hamda mazkur shartnoma shartlariga asosan ajratilgan kreditni hamda u boʻyicha foizlarni qaytarish toʻlov topshiriqnomasi orqali pul oʻtkazish yoʻli bilan amalga oshiriladi. 
                </p>
                <p>
                    5.5.	Qarz oluvchi tomonidan kredit va foizlarni qoplash uchun amalga oshirilgan har qanday toʻlovlar, quyidagi ketma-ketlikda qabul qilinadi:
                </p>
                <p>
                    a) muddatida toʻlanmagan kredit qarzdorligi uchun hisoblangan yuqori foiz;
                </p>
                <p>
                    b) muddatida toʻlanmagan foizlar;
                </p>
                <p>
                    v) muddatida toʻlanmagan asosiy qarz;
                </p>
                <p>
                   g) hisoblangan foiz qarzdorligi;
                </p>
                <p>
                   d) joriy asosiy qarz.
                </p>
                <p>
                  Qarz oluvchi tomonidan kredit boʻyicha asosiy qarz va foizlarni toʻlash muddati oʻtkazib yuborilganda, Bank qarz oluvchining barcha hisobvaragʻidan kerakli summani uning topshirigʻisiz soʻzsiz (akseptsiz) tartibda toʻlov talabnomasi yoki memorial order orqali hisobdan chiqaradi (undirib oladi).
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>6.	KREDIT QAYTARILISHINING TAʼMINOTI VA UNI RASMIYLASHTIRISH</p>
				</div>
				<p>
					6.1.	Mazkur shartnoma asosida ajratilgan kredit,_________________________________________________________ 	(garov, kafolat kafillik) bilan taʼminlanadi.

				</p>
                <p>
                   6.2.	 Bank Qarz oluvchidan kredit qaytarilishi uchun qoʻshimcha taʼminot talab qilish huquqiga ega.
                </p>
                <p>
                    Majburiyat bajarilishining har xil taʼminot turlari mavjudligi bir-biriga zid emas, har bir taʼminot mustaqil boʻlib, bir-biriga bogʻliq boʻlmaydi.
                </p>
                <p>
                    6.3.	 Undiruvni taʼminot predmetiga qaratishga toʻgʻri kelganda, Bank oʻz xohishi bilan undiruvni yoki taʼminotning xohlagan bir turiga yoki hammasiga qaratishga haqli.
                </p>
                <p>
                    6.4.	 Kredit qaytarilishini taʼminoti bilan bogʻliq barcha hujjatlarni rasmiylashtirish xarajatlari Qarz oluvchi tomonidan amalga oshiriladi.
                </p>
                <p>
                    6.5.	 Qarz oluvchi kredit taʼminotini kredit summasining 125 % dan kam boʻlmagan darajada ushlab turish majburiyatini oladi.
                </p>
                <p>
                   6.6.	 Bankning ushbu shartnoma boʻyicha majburiyati (kredit ajratish) kredit olish uchun taqdim etiladigan barcha hujjatlar, xususan, kredit qaytarilishining taʼminlanishini belgilovchi hujjatlar belgilangan tartibda toʻliq rasmiylashtirilgandan va u Bank tomonidan olingandan (ipoteka boʻlgan hollarda - ipoteka shartnomasi notarial tasdiqlangandan, davlat roʻyxatidan oʻtgazilgandan va garovga qoʻyilgan mulk majburiy tartibda sugʻurtalangandan soʻng) soʻng kuchga kiradi.
                </p>
				<br>
		</section>

		<section class="sheet padding-standart">	
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>7.	TOMONLARNING JAVOBGARLIGI</p>
				</div>
				<p>
					7.1.	Asosiy qarzni qaytarish muddati kechiktirilganda (muddati oʻtgan kredit), Qarz oluvchi Bankka butun kechiktirilgan davr uchun shartnomada belgilangan foiz stavkasining 1,5 baravar oshirilgan miqdorida yuqori foiz toʻlaydi.
				</p>
                <p>
                   7.2.	Mazkur shartnomada koʻrsatilgan muddatda kredit ajratilmaganda, Bank qarz oluvchiga kechiktirilgan toʻlovning har bir kuni uchun kechiktirilgan toʻlov summasining 0,1 % miqdorida, ammo kechiktirilgan toʻlov summasining 10 % dan oshmagan miqdorda penya toʻlaydi.
                </p>
                <p>
                   7.3.	Tomonlarning yuqori foiz yoki penyalar toʻlashi shartnoma shartlarini bajarish majburiyatidan ozod qilmaydi.
                </p>
                <p>
                    7.4.	Mazkur shartnomada koʻzda tutilmagan holatlar boʻyicha javobgarliklar Oʻzbekiston Respublikasining amaldagi qonunchiligiga muvofiq oʻrnatiladi.
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>8.	NIZOLARNI HAL ETISH TARTIBI</p>
				</div>
				<p>
					8.1.	Tomonlar ushbu shartnoma yuzasidan kelib chiqishi mumkin boʻlgan kelishmovchilik va nizolarni muzokara hamda maslahatlar yoʻli bilan hal qilishga harakat qiladilar.
				</p>
                <p>
                   8.2.	 Agarda koʻrsatib oʻtilgan kelishmovchilik va nizolar oʻzaro muzokaralar yoʻli bilan hal etilmasa, nizolar Oʻzbekiston Respublikasining amaldagi qonunchiligiga asosan shartnoma imzolangan (BXO/BXM) joylashgan joydagi sudda koʻrib chiqiladi.
                </p>
                <p>
                   8.3.	Ushbu shartnoma bilan bogʻliq boʻlgan har qanday sud jarayonida, shartnomadan kelib chiqqan holda Bankka toʻlanishi lozim boʻlgan barcha pul mablagʻlari boʻyicha Bank hujjatlari mazkur pul mablagʻlari Bankka tegishliligini va unga toʻlab berilishi lozimligini isbotlovchi prima facie (birlamchi) dalil boʻlishi lozim. Xususan, Qarz oluvchining hisobvaraqlaridan Bank koʻchirmalari, agar ularda yaqqol koʻrinib turgan xatoliklar boʻlmasa, Qarz oluvchining shartnoma boʻyicha toʻlov majburiyatlari vujudga kelganligining va/yoki bajarilganligining yakuniy dalili hisoblanadi.
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>9.	SANKSIYALAR BILAN BOGʻLIQ XATARLARNI BOSHQARISH BOʻYICHA SHARTLAR</p>
				</div>
				<p>
					9.1.	Ushbu Shartnoma boʻyicha oʻz majburiyatlarini bajarishda tomonlar ularning har biri oʻz faoliyatida iqtisodiy va moliyaviy sanksiyalar boʻyicha xalqaro qonunchilikka rioya qilishga qaratilgan siyosat va tartiblarga rioya qilishini hamda ularni qoʻllab-quvvatlashini tan oladi va tasdiqlaydi.
				</p>
                <p>
                   9.2.	Bank Qarz oluvchi va uning Kontragenti hamda u  bilan tuzilgan bitim boʻyicha har qanday zarur maʼlumot yoki hujjatlarni (kontragent toʻgʻrisidagi maʼlumotlar, uning toʻliq rekvizitlari, uning affillangan shaxslari roʻyxati, uning aksiyadorlari/muassislari tarkibi, uning ijro organi, mansabdor shaxslari, xodimlari, mahsulot toʻgʻrisida, joʻnatish hujjatlari, mahsulotning spetsifikatsiyasi, tashuvchi toʻgʻrisidagi maʼlumotlar va boshqa zarur maʼlumotlar) ularning sanksiyalar roʻyxatida mavjud va  mavjud emasligini aniqlash maqsadida Qarz oluvchidan talab qilishga haqli. Qarz oluvchi barcha zarur hujjat va maʼlumotlarni taqdim qilmasa, Bank kredit ajratishni rad etish huquqiga ega. 
                </p>
                <p>
                   9.3.	 Bank krediti hisobidan moliyalashtiriladigan shartnomada tomonlardan biri Rossiya, Belarus Respublikasi, Eronda yoki boshqa xalqaro iqtisodiy va moliyaviy sanksiyalar qoʻllanilgan har qanday davlatda roʻyxatdan oʻtgan boʻlsa, Qarz oluvchidan xalqaro eʼtirof etilgan va reytingga ega boʻlgan yuridik kompaniyadan iqtisodiy yoki moliyaviy sanksiyalar boʻyicha xalqaro qonunchilik talablariga muvofiqligi toʻgʻrisida huquqiy xulosani olishga haqli. Ushbu huquqiy xulosa Bank uchun kredit amaliyotini bajarishga majburiy hisoblanmaydi, Bank mazkur amaliyotni oʻtkazishga mustaqil hisoblanadi. 
                </p>
                <p>
                   Qarz oluvchi tomonidan yuridik xulosani olishda qilingan xarajatlar Bank tomonidan qoplanmaydi.
                </p>
                <p>
                   9.4.	 Qarz oluvchi yoki uning operatsiyasi sanksiya taʼsir doirasiga tushganda yoki tushishi xavfi mavjud boʻlganda, Bank operatsiyani oʻrganish maqsadida qoʻshimcha maʼlumotlarni soʻrash, operatsiya miqdorini chegaralash, kredit ajratishni rad etish huquqiga ega. 
                </p>
                <p>
                   9.5.	 Qarz oluvchining kontragentiga (yoki unga xizmat koʻrsatuvchi bankka) nisbatan sanksiyalar rejimiga taalluqli har qanday cheklovlar qoʻllanilgan taqdirda, Qarz oluvchi ularga rioya qilish choralarini koʻrish majburiyatini oladi (huquq va majburiyatlarni sanksiya cheklovlari qoʻllanilmagan boshqa tomonga oʻtkazish, Qarz oluvchi kontragentiga xizmat koʻrsatuvchi bankka sanksiya cheklovlari qoʻllanilgan boʻlsa, ushbu holatda kontragent oʻziga xizmat koʻrsatuvchi bankni sanksiya taqiqlariga tushmagan bankka oʻzgartirish majburiyatini oladi va boshqalar).  Qarz oluvchi tomonidan ushbu talablar bajarilmagan taqdirda, Bank Qarz oluvchiga kredit ajratishni bir tomonlama rad etishga haqli. 
                </p>
                <p>
                   9.6.	 Qarz oluvchining faoliyati sanksiya boʻyicha xalqaro qonunchilikka nomuvofiq boʻlgan taqdirda yoki Bank tomonidan mijozning tashqi savdo operatsiyalarini amalga oshirish rad etilgan hollarda, Bank 5 (besh) ish kuni ichida Qarz oluvchini qoidalar buzilganligini tasdiqlovchi faktlarni/materiallarni ilova qilgan holda yozma ravishdagi xabarnomani quyidagi pochta manziliga yuboradi: 
                </p>
		</section>

		<section class="sheet padding-standart">	
                <p>
                   Bank: ${model.branch_header}
                </p>
                <p>
                  Qarz oluvchi: ${model.sender_name}
                </p>
                <p>
                   9.7.	 Qarz oluvchi ushbu shartlarning 9.6-bandiga asosan, yozma xabarnomada qayd etilgan qoidalarni buzilganlik faktlarini/materiallarini rad etuvchi asoslari mavjud boʻlsa, bu haqida Bankni xabarnoma olingan kunidan boshlab 3 (uch) ish kuni ichida ularni Bankka taqdim etishga haqli.
                </p>
                <p>
                   9.8.	 Qarz oluvchi Bank kreditidan foydalanishda uning kontragenti, kontragentga xizmat koʻrsatuvchi bank, ularning affillangan shaxslari, kontragent aksiyadorlari yoki muassislari, uning ijro organi, ularning mansabdor shaxslari yoki xodimlari, shu bilan birga olinayotgan tovar va xizmatlar sanksiya roʻyxatiga kiritilmaganligini kafolatlaydi.
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>10.	FORS-MAJOR HOLATLAR</p>
				</div>
				<p>
					10.1.	Agar shartnoma imzolangandan soʻng taraflarning erki va istagiga bogʻliq boʻlmagan hamda oldindan koʻra bilib yoki oldini olib boʻlmaydigan, favqulodda vaziyatlar oqibatidagi yengib boʻlmas kuch tufayli taraflar mazkur Shartnoma boʻyicha olgan majburiyatlarini qisman yoki toʻliq bajara olmasalar (fors-major), buning uchun ular javobgar boʻlmaydilar.
				</p>
                <p>
                   Bunda taraflarning hech biri ajratilgan kreditni qaytarish boʻyicha majburiyatdan tashqari, koʻrilishi mumkin boʻlgan zararlarni qoplashni talab qilishga haqli boʻlmaydi.
                </p>
                <p>
                   10.2.	Quyidagilar favqulodda vaziyatlar (fors-major) boʻlib hisoblanadi: suv toshqini, yongʻin, zilzila, portlash, boʻron, yer koʻchkisi, epidemiya va boshqa tabiat hodisalari, urush yoki harbiy harakatlar, fuqarolik tartibsizliklari, terrorchilik harakatlari, hukumat va davlat organlarining aktlari.
                </p>
                <p>
                   10.3.	Taraflar fors-major holatlari vujudga kelganligi va tugaganligi haqida zudlik bilan yozma ravishda bir-birlarini xabardor qilishlari lozim. 
                </p>
                <p>
                   10.4.	Fors-major holatiga asoslanayotgan taraf vakolatli davlat idorasining bunday holatlarning vujudga kelganligini tasdiqlovchi tegishli hujjatini taqdim etishi shart.
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>11. KORRUPSIYAGA QARSHI SHARTLAR</p>
				</div>
				<p>
		           11.1.  Taraflar  ushbu  shartnoma boʻyicha oʻz majburiyatlarini  bajarayotganda ularning har biri oʻz faoliyatida korrupsion harakatlarni toʻliq taqiqlash va har qanday shaklda yordam  (bevosita yoki bilvosita), shu jumladan, pul mablagʻlari, qimmatbaho buyumlar, boshqa mol-mulk yoki mulkiy xarakterdagi xizmatlar, boshqa mulkiy huquqlarni olish/berish, muayyan masalalarni tezroq hal qilishni taʼminlash, maʼmuriy va boshqa tartib-qoidalarni soddalashtirish., raqobat va boshqa afzalliklarni taʼminlashni toʻliq rad etadi. Tomonlar oʻz faoliyatida amaldagi qonunchilik, shuningdek, uning asosida ishlab chiqilgan korrupsiyaga qarshi kurashishga qaratilgan siyosat va tartib (agar mavjud boʻlsa) talablariga amal qiladilar.
				</p>
                <p>
                   11.2. Taraflar ushbu shartnoma boʻyicha oʻz majburiyatlarini bajarish chogʻida na oʻzlari, na ijroiya organi, na ularning masabdor shaxlari yoki xodimlari biron bir shaxslarga (jumladan, jismoniy shaxslar, tijorat tashkilotlari va davlat mansabdor shaxslari) korrupsion toʻlovlarni taqdim etishni taklif qilmasligini, taqdim etmasligini, rozilik bermasligini,  shuningdek, har qanday shaxsdan (toʻgʻridan-toʻgʻri yoki bilvosita) har qanday korrupsion toʻlovlarni olishga yoki qabul qilishga rozi boʻlmasliklarini  kafolatlaydi.
                </p>
                <p>
                   11.3.  Mazkur boʻlimning biron bir shartlari buzilgan taqdirda, tegishli taraf boshqa tarafni bunday buzilish sodir boʻlgan kundan boshlab 5 (besh) ish kuni ichida yozma ravishda xabardor qilish majburiyatini oladi. Taraf yozma xabarnomada ushbu boʻlimning qaysi bir qoidalari buzilganligini tasdiqlovchi ishonchli faktlar va materiallarni taqdim qilishi shart.         
                </p>
                <p>
                   Yozma xabarnomalar “Mikrokreditbank” ATB tomonidan tashkil etilgan jismoniy va yuridik shaxslar uchun korrupsiyaga qarshi kurashish “Komplaens ishonch liniyasi” kanallari (tel: 55-503-77-11, veb sahifa www.mkb.uz, elektron pochta manzili: mkbanticor@mkb.uz, telegramm bot: @mkbanticor_bot) orqali amalga oshiriladi. 
                </p>
                <p>
                    11.4. Ushbu boʻlim qoidalari taraflardan biri tomonidan buzilganligi fakti tasdiqlanganda va/yoki boshqa tarafning qoidabuzarliklarni koʻrib chiqish haqida xabarnoma natijalari  yuzasidan maʼlumot taqdim qilmagan taqdirda, boshqa taraf shartnomani bir taraflama qisman yoki toʻliq bekor qilishga haqli. 
                </p>
                <p>
                    11.5.  Mazkur shartnomani korrupsiyaga qarshi shartlarga asoslanib bekor qilgan taraf, bunday bekor qilish natijasida yetkazilgan haqiqiy zararni talab qilishga haqli. Zararlarni qoplash  taraflar tomonidan yozma ravishda tasdiqlangan dalolatnomada belgilangan muddat va miqdorda amalga oshiriladi.  
                </p>
				<br>
				<div class="part4" style="text-align: center; font-size: 15px; font-weight: 700;">
					<p>12.  BOSHQA SHARTLAR</p>
				</div>
				<p>
		           12.1.	Ushbu shartnoma imzolangan kundan eʼtiboran kuchga kiradi va tomonlar oʻz majburiyatlarini toʻliq bajargunga qadar amalda boʻladi.
				</p>
		</section>

		<section class="sheet padding-standart">	
                <p>
                   12.2.	Ushbu shartnomaning shartlarini oʻzgartirish yoki uni bekor qilish qoʻshimcha kelishuv tuzish orqali amalga oshiriladi. Mazkur shartnomaga kiritiladigan har bir oʻzgartirish va qoʻshimchalar yozma ravishda tuzilib, tomonlarning vakolatli vakillari tomonidan imzolangandan va muhr bilan tasdiqlangandan soʻng haqiqiy hisoblanadi. Barcha oʻzgartirish, qoʻshimchalar va ilovalar mazkur shartnomaning ajralmas qismi boʻlib hisoblanadi.
                </p>
                <p>
                   12.3.	Ushbu shartnoma bekor qilinishida qarz oluvchi kredit boʻyicha asosiy qarzni va hisoblangan foizlarni toʻliq qaytarishi shart.
                </p>
                <p>
                   12.4.	Mazkur shartnomada koʻzda tutilmagan, u bilan bogʻliq boʻlgan barcha munosabatlar Oʻzbekiston Respublikasining amaldagi qonunchiligi bilan tartibga solinadi.
                </p>
                <p>
                    12.5.	Tomonlarning bank rekvizitlari, manzillari oʻzgargan hollarda, albatta, bir-birlarini yozma ravishda xabardor qilishlari shart.
                </p>
                <p>
                    12.6.	Ushbu shartnoma tomonlarning har biri uchun bir xil yuridik kuchga ega boʻlgan ikki nusxada ( ______ varaqda) tuzildi.
                </p>
				<br>

                

                

			<div class="part15" style="text-align: center;font-size: 18px; font-weight: 700;">
				<p>13.	TOMONLARNING YURIDIK MANZILLARI, TOʻLOV REKVIZITLARI, IMZOLARI</p>
			</div>
			<br>
			<div class="part16" style="display: flex;">
				<table>
					<tr>
						<td style="width: 50%;">
							<p style="text-indent: 0px; text-align:center"><b>Bank</p></td>
					<td style="width: 50%;"><p style="text-indent: 0px; text-align:center"><b>Qarz oluvchi</b></p>
						</td>
					</tr>
					<tr>
						<td style="text-align:left">
							<p style="text-indent: 0px; "><b> ${model.bank_branch_name!"-"}</b></p>
							<p style="text-indent: 0px;"><b>Manzil:</b> ${model.post_address!"-"}</p>
							<p style="text-indent: 0px;"><b>STIR:</b> ${model.bank_tin!"-"}</p>
							<p style="text-indent: 0px;"><b>MFO:</b> ${model.bank_mfo!"-"}</p>
							<p style="text-indent: 0px;"><b>H/r:</b> ${model.bank_account!"-"}</p>
							<p style="text-indent: 0px;"><b>tel/faks:</b> ${model.bank_phone!"-"}</p>
							<p style="text-indent: 0px;"><b>Bank filliali boshqaruvchisi</b>: ${model.branch_header!"-"}
							</p>
						</td>
						<td style="text-align:left">
							<p style="text-indent: 0px;"><b>Nomlanishi:</b>${model.sender_type!"-"} ${model.sender_name!"-"}</p>
							<p style="text-indent: 0px;"><b>H/r::</b> ${model.client_account!"-"}</p>
							<p style="text-indent: 0px;"><b>Manzil:</b> ${model.sender_address!"-"}</p>
							<p style="text-indent: 0px;"><b>MFO:</b> ${model.client_mfo!"-"}</p>
							<p style="text-indent: 0px;"><b>STIR:</b>${model.sender_id!"-"}</p>
							<p style="text-indent: 0px;"><b>Tel:</b> +${model.sender_phone!"______________"}</p>
						</td>
					</tr>
				</table>
			</div>

			<table id="sign_block" class="m-t-20">
				<tr valign="top">
					<th valign="top" align="left" width="84px;">
						<img id="doc_qr_code" style="height:80px;width:80px;" src="data:image/jpeg;base64, ${global.documentQrcodeBase64}" alt="QR-code">
			</th>
					<th colspan="2" style="font-weight: normal;">
						<p align="left">
							<b>ЭЛЕКТРОН РАҚАМЛИ ИМЗОЛАР:</b>
						</p>
						<#list signers?if_exists as signer>
							<#assign sIndex=signer?index + 1>
								<#if global.lang=='uz'>
									<p align="left" style="text-indent: 0px;">${sIndex}.
										<span id="s${sIndex}_name">${(signer.fullName)!"-"}</span>
										<br>(стир/жшшир: <span id="s${sIndex}_tin"> ${(signer.signedTin)!"-"} </span>
										сана:
										<span id="s${sIndex}_date"> ${(signer.verifiedAt)!"-"} </span>)</p>
									<#else>
										<p align="left" style="text-indent: 0px;">${sIndex}.
											<span id="s${sIndex}_name">${(signer.fullName)!"-"}</span> <br>(инн:
											<span id="s${sIndex}_tin"> ${(signer.signedTin)!"-"} </span> дата:
											<span id="s${sIndex}_date"> ${(signer.verifiedAt)!"-"} </span>)</p>
								</#if>
								<#else>
									<#if global.lang=='uz'>
										<p align="left" style="text-indent: 0px;">1.
											<span id="s1_name">имзоланмаган</span> (стир/жшшир:
											<span id="s1_tin"> </span> сана: <span id="s1_date"> </span>)</p>
										<p align="left" style="text-indent: 0px;">2.
											<span id="s2_name">имзоланмаган</span> (стир/жшшир:
											<span id="s2_tin"> </span> сана: <span id="s2_date"> </span>)</p>


										<#else>
											<p align="left" style="text-indent: 0px;">1.
												<span id="s1_name">не подписан</span> (инн:
												<span id="s1_tin"> </span> дата: <span id="s1_date"> </span>)</p>
											<p align="left" style="text-indent: 0px;">2.
												<span id="s2_name">не подписан</span> (инн:
												<span id="s2_tin"> </span> дата: <span id="s2_date"> </span>)</p>
									</#if>
						</#list>
					</th>
				</tr>
				<tr>
					<td colspan="3" style="font-weight: normal;">
						<div align="left"><i>${(global.documentUrl)!"-"}</i></div>
					</td>
				</tr>
				<tr>
					<td colspan="3" style="font-weight: normal;">
						<input type="hidden" id="send_params" value='&type=<%= doc_type %>&allow=<%= allow_tins %><%= ((!old_guid.equals(""))?"&old_guid="+old_guid+"&old_pin="+old_pin+"&cancel_date="+cancel_date:"") %>'>
						<input type="hidden" id="doc_params" value="<%= doc_params %>">
						<input type="hidden" id="doc_record_id" value="<%= aid %>">
			</td>
				</tr>
			</table>
		</section>
		<section class="sheet padding-standart">
			<div style="text-align: right">Kredit shartnomasining 2.7 bandi 1-sonli ilova:</div>
			<div style="text-align: right"><b>${model.credit_sum!"-"} so'm, yillik -  ${model.credit_percent!"-"} %</b>
			</div>
			<div class="part11">
				<table>
					<thead>
						<tr>
							<th class="part11t">
								№
							</th>
							<th class="part11t">
								Kreditni qay-<br>tarish sanasi
						</th>
							<th class="part11t">
								Oy oxirida<br>kredit<br>qoldig'i
						</th>
							<th class="part11t">
								Asosiy qarzni<br>qaytarish ulushi
						</th>
							<th class="part11t">
								Foiz<br>to'lov<br>summasi
						</th>
							<th class="part11t">
								Jami<br>to'lov
						</th>
						</tr>
						<tr>
							<th class="part11t">
								1
							</th>
							<th class="part11t">
								2
							</th>
							<th class="part11t">
								3
							</th>
							<th class="part11t">
								4
							</th>
							<th class="part11t">
								5
							</th>
							<th class="part11t">
								6
							</th>
						</tr>
					</thead>
					<#list model.payment_graphs?if_exists as row>
						<#assign sIndex=row?index + 1>
							<#if sIndex lt 120>
								<#if sIndex==35 || sIndex==75 || sIndex==119>
				</table>
		</section>
		<section class="sheet padding-standart">
			<table>
				</#if>
				<tr>
					<td class="part11t">${sIndex!"-"}</td>
					<td class="part11t" style="text-align: left; text-indent: 5px;">${row.payment_time!"-"}</td>
					<td class="part11t">${row.end_residue!"-"}</td>
					<td class="part11t">${row.returned_sum!"-"}</td>
					<td class="part11t">${row.percent_sum!"-"}</td>
					<td class="part11t">${row.payment_total!"-"}</td>
				</tr>
				</#if>
				</#list>
				<#if model.payment_graphs?size lt 120>
					<tr>
						<td class="part11t"></td>
						<td class="part11t">жами:</td>
						<td class="part11t"></td>
						<td class="part11t">${model.returned_sum!"-"}</td>
						<td class="part11t">${model.percent_sum!"-"}</td>
						<td class="part11t">${model.payment_total!"-"}</td>
					</tr>
				</#if>
			</table>
			<#if model.payment_graphs?size==34 || model.payment_graphs?size==74 || model.payment_graphs?size==107>
		</section>
		<section class="sheet padding-standart">
			</#if>
			<table id="sign_block" class="m-t-20">
				<tr valign="top">
					<th valign="top" align="left" width="84px;">
						<img id="doc_qr_code" style="height:80px;width:80px;" src="data:image/jpeg;base64, ${global.documentQrcodeBase64}" alt="QR-code">
					</th>
					<th colspan="2" style="font-weight: normal;">
						<p align="left">
							<b>ЭЛЕКТРОН РАҚАМЛИ ИМЗОЛАР:</b>
						</p>
						<#list signers?if_exists as signer>
							<#assign sIndex=signer?index + 1>
								<#if global.lang=='uz'>
									<p align="left" style="text-indent: 0px;">${sIndex}.
										<span id="s${sIndex}_name">${(signer.fullName)!"-"}</span>
										<br>(стир/жшшир: <span id="s${sIndex}_tin"> ${(signer.signedTin)!"-"} </span>
										сана:
										<span id="s${sIndex}_date"> ${(signer.verifiedAt)!"-"} </span>)</p>
									<#else>
										<p align="left" style="text-indent: 0px;">${sIndex}.
											<span id="s${sIndex}_name">${(signer.fullName)!"-"}</span> <br>(инн:
											<span id="s${sIndex}_tin"> ${(signer.signedTin)!"-"} </span> дата:
											<span id="s${sIndex}_date"> ${(signer.verifiedAt)!"-"} </span>)</p>
								</#if>
								<#else>
									<#if global.lang=='uz'>
										<p align="left" style="text-indent: 0px;">1.
											<span id="s1_name">имзоланмаган</span> (стир/жшшир:
											<span id="s1_tin"> </span> сана: <span id="s1_date"> </span>)</p>
										<p align="left" style="text-indent: 0px;">2.
											<span id="s2_name">имзоланмаган</span> (стир/жшшир:
											<span id="s2_tin"> </span> сана: <span id="s2_date"> </span>)</p>


										<#else>
											<p align="left" style="text-indent: 0px;">1.
												<span id="s1_name">не подписан</span> (инн:
												<span id="s1_tin"> </span> дата: <span id="s1_date"> </span>)</p>
											<p align="left" style="text-indent: 0px;">2.
												<span id="s2_name">не подписан</span> (инн:
												<span id="s2_tin"> </span> дата: <span id="s2_date"> </span>)</p>
									</#if>
						</#list>
					</th>
				</tr>
				<tr>
					<td colspan="3" style="font-weight: normal;">
						<div align="left"><i>${(global.documentUrl)!"-"}</i></div>
					</td>
				</tr>
				<tr>
					<td colspan="3" style="font-weight: normal;">
						<input type="hidden" id="send_params" value='&type=<%= doc_type %>&allow=<%= allow_tins %><%= ((!old_guid.equals(""))?"&old_guid="+old_guid+"&old_pin="+old_pin+"&cancel_date="+cancel_date:"") %>'>
						<input type="hidden" id="doc_params" value="<%= doc_params %>">
						<input type="hidden" id="doc_record_id" value="<%= aid %>">
					</td>
				</tr>
			</table>
			</div>
			</div>
		</section>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<script type="text/javascript"></script>
</body>

</html> 